// Code generated by cramberry. DO NOT EDIT.
// Source: /Volumes/Tendermint/stealth/cramberry/tests/testdata/json_test.cram

import {
  Writer,
  Reader,
  WireTypeV2,
  formatBigIntToString,
  formatNumberToString,
  formatFloat32,
  formatFloat64,
  encodeBase64,
  decodeBase64,
  parseBigIntFromJSON,
  parseNumberFromJSON,
  sortMapKeysLexicographic,
  escapeJSONString,
} from 'cramberry';

// Helper functions for encoding/decoding
function writeArray<T>(writer: Writer, arr: T[], writeElem: (w: Writer, v: T) => void): void {
  const subWriter = new Writer();
  subWriter.writeVarint(arr.length);
  for (const elem of arr) {
    writeElem(subWriter, elem);
  }
  writer.writeLengthPrefixedBytes(subWriter.bytes());
}

function readArray<T>(reader: Reader, readElem: (r: Reader) => T): T[] {
  const data = reader.readLengthPrefixedBytes();
  const subReader = new Reader(data);
  const len = subReader.readVarint();
  const result: T[] = [];
  for (let i = 0; i < len; i++) {
    result.push(readElem(subReader));
  }
  return result;
}

function writeMap<K, V>(writer: Writer, map: Map<K, V> | Record<string, V>, writeKey: (w: Writer, k: K) => void, writeVal: (w: Writer, v: V) => void): void {
  const subWriter = new Writer();
  const entries = map instanceof Map ? Array.from(map.entries()) : Object.entries(map);
  subWriter.writeVarint(entries.length);
  for (const [k, v] of entries) {
    writeKey(subWriter, k as K);
    writeVal(subWriter, v as V);
  }
  writer.writeLengthPrefixedBytes(subWriter.bytes());
}

function readMap<K, V>(reader: Reader, readKey: (r: Reader) => K, readVal: (r: Reader) => V): Map<K, V> {
  const data = reader.readLengthPrefixedBytes();
  const subReader = new Reader(data);
  const len = subReader.readVarint();
  const result = new Map<K, V>();
  for (let i = 0; i < len; i++) {
    const k = readKey(subReader);
    const v = readVal(subReader);
    result.set(k, v);
  }
  return result;
}



export enum Status {
Unknown = 0,
Active = 1,
Inactive = 2,
Pending = 3,
}



export interface ScalarTypes {
boolVal: boolean;
int8Val: number;
int16Val: number;
int32Val: number;
int64Val: bigint;
uint8Val: number;
uint16Val: number;
uint32Val: number;
uint64Val: bigint;
float32Val: number;
float64Val: number;
stringVal: string;
bytesVal: Uint8Array;
}

/** Encodes a ScalarTypes to the writer using V2 wire format. */
export function encodeScalarTypes(writer: Writer, msg: ScalarTypes): void {

  // Field 1: bool_val
  if (msg.boolVal !== undefined && msg.boolVal !== null) {
    writer.writeCompactTag(1, WireTypeV2.Varint);
    writer.writeBool(msg.boolVal);
  }

  // Field 2: int8_val
  if (msg.int8Val !== undefined && msg.int8Val !== null) {
    writer.writeCompactTag(2, WireTypeV2.SVarint);
    writer.writeSVarint(msg.int8Val);
  }

  // Field 3: int16_val
  if (msg.int16Val !== undefined && msg.int16Val !== null) {
    writer.writeCompactTag(3, WireTypeV2.SVarint);
    writer.writeSVarint(msg.int16Val);
  }

  // Field 4: int32_val
  if (msg.int32Val !== undefined && msg.int32Val !== null) {
    writer.writeCompactTag(4, WireTypeV2.SVarint);
    writer.writeSVarint(msg.int32Val);
  }

  // Field 5: int64_val
  if (msg.int64Val !== undefined && msg.int64Val !== null) {
    writer.writeCompactTag(5, WireTypeV2.SVarint);
    writer.writeSVarint64(msg.int64Val);
  }

  // Field 6: uint8_val
  if (msg.uint8Val !== undefined && msg.uint8Val !== null) {
    writer.writeCompactTag(6, WireTypeV2.Varint);
    writer.writeVarint(msg.uint8Val);
  }

  // Field 7: uint16_val
  if (msg.uint16Val !== undefined && msg.uint16Val !== null) {
    writer.writeCompactTag(7, WireTypeV2.Varint);
    writer.writeVarint(msg.uint16Val);
  }

  // Field 8: uint32_val
  if (msg.uint32Val !== undefined && msg.uint32Val !== null) {
    writer.writeCompactTag(8, WireTypeV2.Varint);
    writer.writeVarint(msg.uint32Val);
  }

  // Field 9: uint64_val
  if (msg.uint64Val !== undefined && msg.uint64Val !== null) {
    writer.writeCompactTag(9, WireTypeV2.Varint);
    writer.writeVarint64(msg.uint64Val);
  }

  // Field 10: float32_val
  if (msg.float32Val !== undefined && msg.float32Val !== null) {
    writer.writeCompactTag(10, WireTypeV2.Fixed32);
    writer.writeFloat32(msg.float32Val);
  }

  // Field 11: float64_val
  if (msg.float64Val !== undefined && msg.float64Val !== null) {
    writer.writeCompactTag(11, WireTypeV2.Fixed64);
    writer.writeFloat64(msg.float64Val);
  }

  // Field 12: string_val
  if (msg.stringVal !== undefined && msg.stringVal !== null) {
    writer.writeCompactTag(12, WireTypeV2.Bytes);
    writer.writeString(msg.stringVal);
  }

  // Field 13: bytes_val
  if (msg.bytesVal !== undefined && msg.bytesVal !== null) {
    writer.writeCompactTag(13, WireTypeV2.Bytes);
    writer.writeLengthPrefixedBytes(msg.bytesVal);
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a ScalarTypes from the reader using V2 wire format. */
export function decodeScalarTypes(reader: Reader): ScalarTypes {
  const result: Partial<ScalarTypes> = {};

  while (true) {
    const { fieldNum, wireType } = reader.readCompactTag();
    if (fieldNum === 0) break; // End marker

    switch (fieldNum) {
      case 1:
        result.boolVal = reader.readBool();
        break;
      case 2:
        result.int8Val = reader.readSVarint();
        break;
      case 3:
        result.int16Val = reader.readSVarint();
        break;
      case 4:
        result.int32Val = reader.readSVarint();
        break;
      case 5:
        result.int64Val = reader.readSVarint64();
        break;
      case 6:
        result.uint8Val = reader.readVarint();
        break;
      case 7:
        result.uint16Val = reader.readVarint();
        break;
      case 8:
        result.uint32Val = reader.readVarint();
        break;
      case 9:
        result.uint64Val = reader.readVarint64();
        break;
      case 10:
        result.float32Val = reader.readFloat32();
        break;
      case 11:
        result.float64Val = reader.readFloat64();
        break;
      case 12:
        result.stringVal = reader.readString();
        break;
      case 13:
        result.bytesVal = reader.readLengthPrefixedBytes();
        break;
      default:
        reader.skipValueV2(wireType);
    }
  }

  return result as ScalarTypes;
}

/** Marshals a ScalarTypes to bytes. */
export function marshalScalarTypes(msg: ScalarTypes): Uint8Array {
  const writer = new Writer();
  encodeScalarTypes(writer, msg);
  return writer.bytes();
}

/** Unmarshals a ScalarTypes from bytes. */
export function unmarshalScalarTypes(data: Uint8Array): ScalarTypes {
  const reader = new Reader(data);
  return decodeScalarTypes(reader);
}

/** Encodes a ScalarTypes to deterministic JSON format. */
export function toJSON_ScalarTypes(msg: ScalarTypes): string {
  let result = '{';

  result += '"bool_val":';
  result += msg.boolVal ? 'true' : 'false';

  result += ',';
  result += '"int8_val":';
  result += '"' + formatNumberToString(msg.int8Val) + '"';

  result += ',';
  result += '"int16_val":';
  result += '"' + formatNumberToString(msg.int16Val) + '"';

  result += ',';
  result += '"int32_val":';
  result += '"' + formatNumberToString(msg.int32Val) + '"';

  result += ',';
  result += '"int64_val":';
  result += '"' + formatBigIntToString(msg.int64Val) + '"';

  result += ',';
  result += '"uint8_val":';
  result += '"' + formatNumberToString(msg.uint8Val) + '"';

  result += ',';
  result += '"uint16_val":';
  result += '"' + formatNumberToString(msg.uint16Val) + '"';

  result += ',';
  result += '"uint32_val":';
  result += '"' + formatNumberToString(msg.uint32Val) + '"';

  result += ',';
  result += '"uint64_val":';
  result += '"' + formatBigIntToString(msg.uint64Val) + '"';

  result += ',';
  result += '"float32_val":';
  result += formatFloat32(msg.float32Val);

  result += ',';
  result += '"float64_val":';
  result += formatFloat64(msg.float64Val);

  result += ',';
  result += '"string_val":';
  result += escapeJSONString(msg.stringVal);

  result += ',';
  result += '"bytes_val":';
  result += '"' + encodeBase64(msg.bytesVal) + '"';

  result += '}';
  return result;
}

/** Decodes a ScalarTypes from JSON format. */
export function fromJSON_ScalarTypes(json: string): ScalarTypes {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode)
  const allowedFields = new Set([
    'bool_val',
    'int8_val',
    'int16_val',
    'int32_val',
    'int64_val',
    'uint8_val',
    'uint16_val',
    'uint32_val',
    'uint64_val',
    'float32_val',
    'float64_val',
    'string_val',
    'bytes_val',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  const msg: Partial<ScalarTypes> = {};

  // Decode fields

  if ('bool_val' in obj) {
    const value = obj['bool_val'];
    msg.boolVal = Boolean(value);
  }

  if ('int8_val' in obj) {
    const value = obj['int8_val'];
    msg.int8Val = parseNumberFromJSON(value);
  }

  if ('int16_val' in obj) {
    const value = obj['int16_val'];
    msg.int16Val = parseNumberFromJSON(value);
  }

  if ('int32_val' in obj) {
    const value = obj['int32_val'];
    msg.int32Val = parseNumberFromJSON(value);
  }

  if ('int64_val' in obj) {
    const value = obj['int64_val'];
    msg.int64Val = parseBigIntFromJSON(value);
  }

  if ('uint8_val' in obj) {
    const value = obj['uint8_val'];
    msg.uint8Val = parseNumberFromJSON(value);
  }

  if ('uint16_val' in obj) {
    const value = obj['uint16_val'];
    msg.uint16Val = parseNumberFromJSON(value);
  }

  if ('uint32_val' in obj) {
    const value = obj['uint32_val'];
    msg.uint32Val = parseNumberFromJSON(value);
  }

  if ('uint64_val' in obj) {
    const value = obj['uint64_val'];
    msg.uint64Val = parseBigIntFromJSON(value);
  }

  if ('float32_val' in obj) {
    const value = obj['float32_val'];
    msg.float32Val = Number(value);
  }

  if ('float64_val' in obj) {
    const value = obj['float64_val'];
    msg.float64Val = Number(value);
  }

  if ('string_val' in obj) {
    const value = obj['string_val'];
    msg.stringVal = String(value);
  }

  if ('bytes_val' in obj) {
    const value = obj['bytes_val'];
    msg.bytesVal = decodeBase64(String(value));
  }


  return msg as ScalarTypes;
}


export interface RepeatedTypes {
strings: string[];
ints: bigint[];
bools: boolean[];
}

/** Encodes a RepeatedTypes to the writer using V2 wire format. */
export function encodeRepeatedTypes(writer: Writer, msg: RepeatedTypes): void {

  // Field 1: strings
  if (msg.strings !== undefined && msg.strings !== null) {
    writer.writeCompactTag(1, WireTypeV2.Bytes);
    writeArray(writer, msg.strings, (w, v) => { w.writeString(v) });
  }

  // Field 2: ints
  if (msg.ints !== undefined && msg.ints !== null) {
    writer.writeCompactTag(2, WireTypeV2.SVarint);
    writeArray(writer, msg.ints, (w, v) => { w.writeSVarint64(v) });
  }

  // Field 3: bools
  if (msg.bools !== undefined && msg.bools !== null) {
    writer.writeCompactTag(3, WireTypeV2.Varint);
    writeArray(writer, msg.bools, (w, v) => { w.writeBool(v) });
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a RepeatedTypes from the reader using V2 wire format. */
export function decodeRepeatedTypes(reader: Reader): RepeatedTypes {
  const result: Partial<RepeatedTypes> = {};

  while (true) {
    const { fieldNum, wireType } = reader.readCompactTag();
    if (fieldNum === 0) break; // End marker

    switch (fieldNum) {
      case 1:
        result.strings = readArray(reader, (r) => reader.readString());
        break;
      case 2:
        result.ints = readArray(reader, (r) => reader.readSVarint64());
        break;
      case 3:
        result.bools = readArray(reader, (r) => reader.readBool());
        break;
      default:
        reader.skipValueV2(wireType);
    }
  }

  return result as RepeatedTypes;
}

/** Marshals a RepeatedTypes to bytes. */
export function marshalRepeatedTypes(msg: RepeatedTypes): Uint8Array {
  const writer = new Writer();
  encodeRepeatedTypes(writer, msg);
  return writer.bytes();
}

/** Unmarshals a RepeatedTypes from bytes. */
export function unmarshalRepeatedTypes(data: Uint8Array): RepeatedTypes {
  const reader = new Reader(data);
  return decodeRepeatedTypes(reader);
}

/** Encodes a RepeatedTypes to deterministic JSON format. */
export function toJSON_RepeatedTypes(msg: RepeatedTypes): string {
  let result = '{';

  result += '"strings":';
  result += '[';
  for (let i = 0; i < msg.strings.length; i++) {
    if (i > 0) result += ',';
    const elem = msg.strings[i];
    result += escapeJSONString(elem);
  }
  result += ']';

  result += ',';
  result += '"ints":';
  result += '[';
  for (let i = 0; i < msg.ints.length; i++) {
    if (i > 0) result += ',';
    const elem = msg.ints[i];
    result += '"' + formatBigIntToString(elem) + '"';
  }
  result += ']';

  result += ',';
  result += '"bools":';
  result += '[';
  for (let i = 0; i < msg.bools.length; i++) {
    if (i > 0) result += ',';
    const elem = msg.bools[i];
    result += elem ? 'true' : 'false';
  }
  result += ']';

  result += '}';
  return result;
}

/** Decodes a RepeatedTypes from JSON format. */
export function fromJSON_RepeatedTypes(json: string): RepeatedTypes {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode)
  const allowedFields = new Set([
    'strings',
    'ints',
    'bools',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  const msg: Partial<RepeatedTypes> = {};

  // Decode fields

  if ('strings' in obj) {
    const value = obj['strings'];
    if (!Array.isArray(value)) throw new Error('expected array');
    msg.strings = [];
    for (const elem of value) {
      let decoded: string;
      decoded = String(elem);
      msg.strings.push(decoded);
    }
  }

  if ('ints' in obj) {
    const value = obj['ints'];
    if (!Array.isArray(value)) throw new Error('expected array');
    msg.ints = [];
    for (const elem of value) {
      let decoded: bigint;
      decoded = parseBigIntFromJSON(elem);
      msg.ints.push(decoded);
    }
  }

  if ('bools' in obj) {
    const value = obj['bools'];
    if (!Array.isArray(value)) throw new Error('expected array');
    msg.bools = [];
    for (const elem of value) {
      let decoded: boolean;
      decoded = Boolean(elem);
      msg.bools.push(decoded);
    }
  }


  return msg as RepeatedTypes;
}


export interface MapTypes {
stringMap: Record<string, string>;
intMap: Record<string, bigint>;
}

/** Encodes a MapTypes to the writer using V2 wire format. */
export function encodeMapTypes(writer: Writer, msg: MapTypes): void {

  // Field 1: string_map
  if (msg.stringMap !== undefined && msg.stringMap !== null) {
    writer.writeCompactTag(1, WireTypeV2.Bytes);
    writeMap(writer, msg.stringMap, (w, k) => { w.writeString(k) }, (w, v) => { w.writeString(v) });
  }

  // Field 2: int_map
  if (msg.intMap !== undefined && msg.intMap !== null) {
    writer.writeCompactTag(2, WireTypeV2.Bytes);
    writeMap(writer, msg.intMap, (w, k) => { w.writeString(k) }, (w, v) => { w.writeSVarint64(v) });
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a MapTypes from the reader using V2 wire format. */
export function decodeMapTypes(reader: Reader): MapTypes {
  const result: Partial<MapTypes> = {};

  while (true) {
    const { fieldNum, wireType } = reader.readCompactTag();
    if (fieldNum === 0) break; // End marker

    switch (fieldNum) {
      case 1:
        result.stringMap = readMap(reader, (r) => reader.readString(), (r) => reader.readString());
        break;
      case 2:
        result.intMap = readMap(reader, (r) => reader.readString(), (r) => reader.readSVarint64());
        break;
      default:
        reader.skipValueV2(wireType);
    }
  }

  return result as MapTypes;
}

/** Marshals a MapTypes to bytes. */
export function marshalMapTypes(msg: MapTypes): Uint8Array {
  const writer = new Writer();
  encodeMapTypes(writer, msg);
  return writer.bytes();
}

/** Unmarshals a MapTypes from bytes. */
export function unmarshalMapTypes(data: Uint8Array): MapTypes {
  const reader = new Reader(data);
  return decodeMapTypes(reader);
}

/** Encodes a MapTypes to deterministic JSON format. */
export function toJSON_MapTypes(msg: MapTypes): string {
  let result = '{';

  result += '"string_map":';
  {
    result += '{';
    const keys = Array.from(msg.stringMap.keys());
    const sortedKeys = sortMapKeysLexicographic(keys);
    for (let i = 0; i < sortedKeys.length; i++) {
      if (i > 0) result += ',';
      result += escapeJSONString(sortedKeys[i]) + ':';
      const k = sortedKeys[i];
      const v = msg.stringMap.get(k)!;
      result += escapeJSONString(v);
    }
    result += '}';
  }

  result += ',';
  result += '"int_map":';
  {
    result += '{';
    const keys = Array.from(msg.intMap.keys());
    const sortedKeys = sortMapKeysLexicographic(keys);
    for (let i = 0; i < sortedKeys.length; i++) {
      if (i > 0) result += ',';
      result += escapeJSONString(sortedKeys[i]) + ':';
      const k = sortedKeys[i];
      const v = msg.intMap.get(k)!;
      result += '"' + formatBigIntToString(v) + '"';
    }
    result += '}';
  }

  result += '}';
  return result;
}

/** Decodes a MapTypes from JSON format. */
export function fromJSON_MapTypes(json: string): MapTypes {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode)
  const allowedFields = new Set([
    'string_map',
    'int_map',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  const msg: Partial<MapTypes> = {};

  // Decode fields

  if ('string_map' in obj) {
    const value = obj['string_map'];
    if (typeof value !== 'object' || value === null) throw new Error('expected object');
    msg.stringMap = new Map();
    for (const [keyStr, val] of Object.entries(value)) {
      const k = keyStr;
      let v: string;
      v = String(val);
      msg.stringMap.set(k, v);
    }
  }

  if ('int_map' in obj) {
    const value = obj['int_map'];
    if (typeof value !== 'object' || value === null) throw new Error('expected object');
    msg.intMap = new Map();
    for (const [keyStr, val] of Object.entries(value)) {
      const k = keyStr;
      let v: bigint;
      v = parseBigIntFromJSON(val);
      msg.intMap.set(k, v);
    }
  }


  return msg as MapTypes;
}


export interface Address {
street: string;
city: string;
zip: string;
}

/** Encodes a Address to the writer using V2 wire format. */
export function encodeAddress(writer: Writer, msg: Address): void {

  // Field 1: street
  if (msg.street !== undefined && msg.street !== null) {
    writer.writeCompactTag(1, WireTypeV2.Bytes);
    writer.writeString(msg.street);
  }

  // Field 2: city
  if (msg.city !== undefined && msg.city !== null) {
    writer.writeCompactTag(2, WireTypeV2.Bytes);
    writer.writeString(msg.city);
  }

  // Field 3: zip
  if (msg.zip !== undefined && msg.zip !== null) {
    writer.writeCompactTag(3, WireTypeV2.Bytes);
    writer.writeString(msg.zip);
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a Address from the reader using V2 wire format. */
export function decodeAddress(reader: Reader): Address {
  const result: Partial<Address> = {};

  while (true) {
    const { fieldNum, wireType } = reader.readCompactTag();
    if (fieldNum === 0) break; // End marker

    switch (fieldNum) {
      case 1:
        result.street = reader.readString();
        break;
      case 2:
        result.city = reader.readString();
        break;
      case 3:
        result.zip = reader.readString();
        break;
      default:
        reader.skipValueV2(wireType);
    }
  }

  return result as Address;
}

/** Marshals a Address to bytes. */
export function marshalAddress(msg: Address): Uint8Array {
  const writer = new Writer();
  encodeAddress(writer, msg);
  return writer.bytes();
}

/** Unmarshals a Address from bytes. */
export function unmarshalAddress(data: Uint8Array): Address {
  const reader = new Reader(data);
  return decodeAddress(reader);
}

/** Encodes a Address to deterministic JSON format. */
export function toJSON_Address(msg: Address): string {
  let result = '{';

  result += '"street":';
  result += escapeJSONString(msg.street);

  result += ',';
  result += '"city":';
  result += escapeJSONString(msg.city);

  result += ',';
  result += '"zip":';
  result += escapeJSONString(msg.zip);

  result += '}';
  return result;
}

/** Decodes a Address from JSON format. */
export function fromJSON_Address(json: string): Address {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode)
  const allowedFields = new Set([
    'street',
    'city',
    'zip',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  const msg: Partial<Address> = {};

  // Decode fields

  if ('street' in obj) {
    const value = obj['street'];
    msg.street = String(value);
  }

  if ('city' in obj) {
    const value = obj['city'];
    msg.city = String(value);
  }

  if ('zip' in obj) {
    const value = obj['zip'];
    msg.zip = String(value);
  }


  return msg as Address;
}


export interface Person {
name: string;
age: number;
address: Address;
emails: string[];
}

/** Encodes a Person to the writer using V2 wire format. */
export function encodePerson(writer: Writer, msg: Person): void {

  // Field 1: name
  if (msg.name !== undefined && msg.name !== null) {
    writer.writeCompactTag(1, WireTypeV2.Bytes);
    writer.writeString(msg.name);
  }

  // Field 2: age
  if (msg.age !== undefined && msg.age !== null) {
    writer.writeCompactTag(2, WireTypeV2.SVarint);
    writer.writeSVarint(msg.age);
  }

  // Field 3: address
  if (msg.address !== undefined && msg.address !== null) {
    writer.writeCompactTag(3, WireTypeV2.Bytes);
    encodeAddress(writer, msg.address);
  }

  // Field 4: emails
  if (msg.emails !== undefined && msg.emails !== null) {
    writer.writeCompactTag(4, WireTypeV2.Bytes);
    writeArray(writer, msg.emails, (w, v) => { w.writeString(v) });
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a Person from the reader using V2 wire format. */
export function decodePerson(reader: Reader): Person {
  const result: Partial<Person> = {};

  while (true) {
    const { fieldNum, wireType } = reader.readCompactTag();
    if (fieldNum === 0) break; // End marker

    switch (fieldNum) {
      case 1:
        result.name = reader.readString();
        break;
      case 2:
        result.age = reader.readSVarint();
        break;
      case 3:
        result.address = decodeAddress(reader);
        break;
      case 4:
        result.emails = readArray(reader, (r) => reader.readString());
        break;
      default:
        reader.skipValueV2(wireType);
    }
  }

  return result as Person;
}

/** Marshals a Person to bytes. */
export function marshalPerson(msg: Person): Uint8Array {
  const writer = new Writer();
  encodePerson(writer, msg);
  return writer.bytes();
}

/** Unmarshals a Person from bytes. */
export function unmarshalPerson(data: Uint8Array): Person {
  const reader = new Reader(data);
  return decodePerson(reader);
}

/** Encodes a Person to deterministic JSON format. */
export function toJSON_Person(msg: Person): string {
  let result = '{';

  result += '"name":';
  result += escapeJSONString(msg.name);

  result += ',';
  result += '"age":';
  result += '"' + formatNumberToString(msg.age) + '"';

  result += ',';
  result += '"address":';
  result += JSON.stringify(msg.address);

  result += ',';
  result += '"emails":';
  result += '[';
  for (let i = 0; i < msg.emails.length; i++) {
    if (i > 0) result += ',';
    const elem = msg.emails[i];
    result += escapeJSONString(elem);
  }
  result += ']';

  result += '}';
  return result;
}

/** Decodes a Person from JSON format. */
export function fromJSON_Person(json: string): Person {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode)
  const allowedFields = new Set([
    'name',
    'age',
    'address',
    'emails',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  const msg: Partial<Person> = {};

  // Decode fields

  if ('name' in obj) {
    const value = obj['name'];
    msg.name = String(value);
  }

  if ('age' in obj) {
    const value = obj['age'];
    msg.age = parseNumberFromJSON(value);
  }

  if ('address' in obj) {
    const value = obj['address'];
    msg.address = fromJSON_Address(JSON.stringify(value));
  }

  if ('emails' in obj) {
    const value = obj['emails'];
    if (!Array.isArray(value)) throw new Error('expected array');
    msg.emails = [];
    for (const elem of value) {
      let decoded: string;
      decoded = String(elem);
      msg.emails.push(decoded);
    }
  }


  return msg as Person;
}


export interface RequiredFields {
id: bigint;
name: string;
optionalField: string;
}

/** Encodes a RequiredFields to the writer using V2 wire format. */
export function encodeRequiredFields(writer: Writer, msg: RequiredFields): void {

  // Field 1: id
  if (msg.id !== undefined && msg.id !== null) {
    writer.writeCompactTag(1, WireTypeV2.SVarint);
    writer.writeSVarint64(msg.id);
  }

  // Field 2: name
  if (msg.name !== undefined && msg.name !== null) {
    writer.writeCompactTag(2, WireTypeV2.Bytes);
    writer.writeString(msg.name);
  }

  // Field 3: optional_field
  if (msg.optionalField !== undefined && msg.optionalField !== null) {
    writer.writeCompactTag(3, WireTypeV2.Bytes);
    writer.writeString(msg.optionalField);
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a RequiredFields from the reader using V2 wire format. */
export function decodeRequiredFields(reader: Reader): RequiredFields {
  const result: Partial<RequiredFields> = {};

  while (true) {
    const { fieldNum, wireType } = reader.readCompactTag();
    if (fieldNum === 0) break; // End marker

    switch (fieldNum) {
      case 1:
        result.id = reader.readSVarint64();
        break;
      case 2:
        result.name = reader.readString();
        break;
      case 3:
        result.optionalField = reader.readString();
        break;
      default:
        reader.skipValueV2(wireType);
    }
  }

  return result as RequiredFields;
}

/** Marshals a RequiredFields to bytes. */
export function marshalRequiredFields(msg: RequiredFields): Uint8Array {
  const writer = new Writer();
  encodeRequiredFields(writer, msg);
  return writer.bytes();
}

/** Unmarshals a RequiredFields from bytes. */
export function unmarshalRequiredFields(data: Uint8Array): RequiredFields {
  const reader = new Reader(data);
  return decodeRequiredFields(reader);
}

/** Encodes a RequiredFields to deterministic JSON format. */
export function toJSON_RequiredFields(msg: RequiredFields): string {
  let result = '{';

  result += '"id":';
  result += '"' + formatBigIntToString(msg.id) + '"';

  result += ',';
  result += '"name":';
  result += escapeJSONString(msg.name);

  result += ',';
  result += '"optional_field":';
  result += escapeJSONString(msg.optionalField);

  result += '}';
  return result;
}

/** Decodes a RequiredFields from JSON format. */
export function fromJSON_RequiredFields(json: string): RequiredFields {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode)
  const allowedFields = new Set([
    'id',
    'name',
    'optional_field',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  const msg: Partial<RequiredFields> = {};

  // Decode fields

  if ('id' in obj) {
    const value = obj['id'];
    msg.id = parseBigIntFromJSON(value);
  }

  if ('name' in obj) {
    const value = obj['name'];
    msg.name = String(value);
  }

  if ('optional_field' in obj) {
    const value = obj['optional_field'];
    msg.optionalField = String(value);
  }


  return msg as RequiredFields;
}


export interface OptionalPointer {
value: string | null;
number: bigint | null;
}

/** Encodes a OptionalPointer to the writer using V2 wire format. */
export function encodeOptionalPointer(writer: Writer, msg: OptionalPointer): void {

  // Field 1: value
  if (msg.value !== undefined && msg.value !== null) {
    writer.writeCompactTag(1, WireTypeV2.Bytes);
    if (msg.value !== null) { writer.writeString(msg.value) };
  }

  // Field 2: number
  if (msg.number !== undefined && msg.number !== null) {
    writer.writeCompactTag(2, WireTypeV2.Bytes);
    if (msg.number !== null) { writer.writeSVarint64(msg.number) };
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a OptionalPointer from the reader using V2 wire format. */
export function decodeOptionalPointer(reader: Reader): OptionalPointer {
  const result: Partial<OptionalPointer> = {};

  while (true) {
    const { fieldNum, wireType } = reader.readCompactTag();
    if (fieldNum === 0) break; // End marker

    switch (fieldNum) {
      case 1:
        result.value = reader.readString();
        break;
      case 2:
        result.number = reader.readSVarint64();
        break;
      default:
        reader.skipValueV2(wireType);
    }
  }

  return result as OptionalPointer;
}

/** Marshals a OptionalPointer to bytes. */
export function marshalOptionalPointer(msg: OptionalPointer): Uint8Array {
  const writer = new Writer();
  encodeOptionalPointer(writer, msg);
  return writer.bytes();
}

/** Unmarshals a OptionalPointer from bytes. */
export function unmarshalOptionalPointer(data: Uint8Array): OptionalPointer {
  const reader = new Reader(data);
  return decodeOptionalPointer(reader);
}

/** Encodes a OptionalPointer to deterministic JSON format. */
export function toJSON_OptionalPointer(msg: OptionalPointer): string {
  let result = '{';

  result += '"value":';
  if (msg.value != null) {
      result += escapeJSONString(msg.value);
  } else {
    result += 'null';
  }

  result += ',';
  result += '"number":';
  if (msg.number != null) {
      result += '"' + formatBigIntToString(msg.number) + '"';
  } else {
    result += 'null';
  }

  result += '}';
  return result;
}

/** Decodes a OptionalPointer from JSON format. */
export function fromJSON_OptionalPointer(json: string): OptionalPointer {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode)
  const allowedFields = new Set([
    'value',
    'number',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  const msg: Partial<OptionalPointer> = {};

  // Decode fields

  if ('value' in obj) {
    const value = obj['value'];
    if (value != null) {
      msg.value = String(value);
    } else {
      msg.value = null;
    }
  }

  if ('number' in obj) {
    const value = obj['number'];
    if (value != null) {
      msg.number = parseBigIntFromJSON(value);
    } else {
      msg.number = null;
    }
  }


  return msg as OptionalPointer;
}


export interface EnumTest {
status: Status;
statuses: Status[];
}

/** Encodes a EnumTest to the writer using V2 wire format. */
export function encodeEnumTest(writer: Writer, msg: EnumTest): void {

  // Field 1: status
  if (msg.status !== undefined && msg.status !== null) {
    writer.writeCompactTag(1, WireTypeV2.SVarint);
    writer.writeSVarint(msg.status);
  }

  // Field 2: statuses
  if (msg.statuses !== undefined && msg.statuses !== null) {
    writer.writeCompactTag(2, WireTypeV2.SVarint);
    writeArray(writer, msg.statuses, (w, v) => { w.writeSVarint(v) });
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a EnumTest from the reader using V2 wire format. */
export function decodeEnumTest(reader: Reader): EnumTest {
  const result: Partial<EnumTest> = {};

  while (true) {
    const { fieldNum, wireType } = reader.readCompactTag();
    if (fieldNum === 0) break; // End marker

    switch (fieldNum) {
      case 1:
        result.status = reader.readSVarint();
        break;
      case 2:
        result.statuses = readArray(reader, (r) => reader.readSVarint());
        break;
      default:
        reader.skipValueV2(wireType);
    }
  }

  return result as EnumTest;
}

/** Marshals a EnumTest to bytes. */
export function marshalEnumTest(msg: EnumTest): Uint8Array {
  const writer = new Writer();
  encodeEnumTest(writer, msg);
  return writer.bytes();
}

/** Unmarshals a EnumTest from bytes. */
export function unmarshalEnumTest(data: Uint8Array): EnumTest {
  const reader = new Reader(data);
  return decodeEnumTest(reader);
}

/** Encodes a EnumTest to deterministic JSON format. */
export function toJSON_EnumTest(msg: EnumTest): string {
  let result = '{';

  result += '"status":';
  result += '"' + msg.status.toString() + '"';

  result += ',';
  result += '"statuses":';
  result += '[';
  for (let i = 0; i < msg.statuses.length; i++) {
    if (i > 0) result += ',';
    const elem = msg.statuses[i];
    result += '"' + elem.toString() + '"';
  }
  result += ']';

  result += '}';
  return result;
}

/** Decodes a EnumTest from JSON format. */
export function fromJSON_EnumTest(json: string): EnumTest {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode)
  const allowedFields = new Set([
    'status',
    'statuses',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  const msg: Partial<EnumTest> = {};

  // Decode fields

  if ('status' in obj) {
    const value = obj['status'];
    const strVal = String(value);
    switch (strVal) {
      case 'UNKNOWN':
        msg.status = Status.Unknown;
        break;
      case 'ACTIVE':
        msg.status = Status.Active;
        break;
      case 'INACTIVE':
        msg.status = Status.Inactive;
        break;
      case 'PENDING':
        msg.status = Status.Pending;
        break;
      default:
        throw new Error(`unknown enum value: ${strVal}`);
    }
  }

  if ('statuses' in obj) {
    const value = obj['statuses'];
    if (!Array.isArray(value)) throw new Error('expected array');
    msg.statuses = [];
    for (const elem of value) {
      let decoded: Status;
      const strVal = String(elem);
      switch (strVal) {
        case 'UNKNOWN':
            decoded = Status.Unknown;
            break;
        case 'ACTIVE':
            decoded = Status.Active;
            break;
        case 'INACTIVE':
            decoded = Status.Inactive;
            break;
        case 'PENDING':
            decoded = Status.Pending;
            break;
        default:
            throw new Error(`unknown enum value: ${strVal}`);
      }
      msg.statuses.push(decoded);
    }
  }


  return msg as EnumTest;
}


export interface EmptyMessage {
}

/** Encodes a EmptyMessage to the writer using V2 wire format. */
export function encodeEmptyMessage(writer: Writer, msg: EmptyMessage): void {
// End marker
  writer.writeEndMarker();
}

/** Decodes a EmptyMessage from the reader using V2 wire format. */
export function decodeEmptyMessage(reader: Reader): EmptyMessage {
  const result: Partial<EmptyMessage> = {};

  while (true) {
    const { fieldNum, wireType } = reader.readCompactTag();
    if (fieldNum === 0) break; // End marker

    switch (fieldNum) {
      default:
        reader.skipValueV2(wireType);
    }
  }

  return result as EmptyMessage;
}

/** Marshals a EmptyMessage to bytes. */
export function marshalEmptyMessage(msg: EmptyMessage): Uint8Array {
  const writer = new Writer();
  encodeEmptyMessage(writer, msg);
  return writer.bytes();
}

/** Unmarshals a EmptyMessage from bytes. */
export function unmarshalEmptyMessage(data: Uint8Array): EmptyMessage {
  const reader = new Reader(data);
  return decodeEmptyMessage(reader);
}

/** Encodes a EmptyMessage to deterministic JSON format. */
export function toJSON_EmptyMessage(msg: EmptyMessage): string {
  let result = '{';

  result += '}';
  return result;
}

/** Decodes a EmptyMessage from JSON format. */
export function fromJSON_EmptyMessage(json: string): EmptyMessage {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode)
  const allowedFields = new Set([
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  const msg: Partial<EmptyMessage> = {};

  // Decode fields


  return msg as EmptyMessage;
}


export interface AllZeroValues {
zeroInt: bigint;
zeroString: string;
zeroBool: boolean;
emptyArray: string[];
}

/** Encodes a AllZeroValues to the writer using V2 wire format. */
export function encodeAllZeroValues(writer: Writer, msg: AllZeroValues): void {

  // Field 1: zero_int
  if (msg.zeroInt !== undefined && msg.zeroInt !== null) {
    writer.writeCompactTag(1, WireTypeV2.SVarint);
    writer.writeSVarint64(msg.zeroInt);
  }

  // Field 2: zero_string
  if (msg.zeroString !== undefined && msg.zeroString !== null) {
    writer.writeCompactTag(2, WireTypeV2.Bytes);
    writer.writeString(msg.zeroString);
  }

  // Field 3: zero_bool
  if (msg.zeroBool !== undefined && msg.zeroBool !== null) {
    writer.writeCompactTag(3, WireTypeV2.Varint);
    writer.writeBool(msg.zeroBool);
  }

  // Field 4: empty_array
  if (msg.emptyArray !== undefined && msg.emptyArray !== null) {
    writer.writeCompactTag(4, WireTypeV2.Bytes);
    writeArray(writer, msg.emptyArray, (w, v) => { w.writeString(v) });
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a AllZeroValues from the reader using V2 wire format. */
export function decodeAllZeroValues(reader: Reader): AllZeroValues {
  const result: Partial<AllZeroValues> = {};

  while (true) {
    const { fieldNum, wireType } = reader.readCompactTag();
    if (fieldNum === 0) break; // End marker

    switch (fieldNum) {
      case 1:
        result.zeroInt = reader.readSVarint64();
        break;
      case 2:
        result.zeroString = reader.readString();
        break;
      case 3:
        result.zeroBool = reader.readBool();
        break;
      case 4:
        result.emptyArray = readArray(reader, (r) => reader.readString());
        break;
      default:
        reader.skipValueV2(wireType);
    }
  }

  return result as AllZeroValues;
}

/** Marshals a AllZeroValues to bytes. */
export function marshalAllZeroValues(msg: AllZeroValues): Uint8Array {
  const writer = new Writer();
  encodeAllZeroValues(writer, msg);
  return writer.bytes();
}

/** Unmarshals a AllZeroValues from bytes. */
export function unmarshalAllZeroValues(data: Uint8Array): AllZeroValues {
  const reader = new Reader(data);
  return decodeAllZeroValues(reader);
}

/** Encodes a AllZeroValues to deterministic JSON format. */
export function toJSON_AllZeroValues(msg: AllZeroValues): string {
  let result = '{';

  result += '"zero_int":';
  result += '"' + formatBigIntToString(msg.zeroInt) + '"';

  result += ',';
  result += '"zero_string":';
  result += escapeJSONString(msg.zeroString);

  result += ',';
  result += '"zero_bool":';
  result += msg.zeroBool ? 'true' : 'false';

  result += ',';
  result += '"empty_array":';
  result += '[';
  for (let i = 0; i < msg.emptyArray.length; i++) {
    if (i > 0) result += ',';
    const elem = msg.emptyArray[i];
    result += escapeJSONString(elem);
  }
  result += ']';

  result += '}';
  return result;
}

/** Decodes a AllZeroValues from JSON format. */
export function fromJSON_AllZeroValues(json: string): AllZeroValues {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode)
  const allowedFields = new Set([
    'zero_int',
    'zero_string',
    'zero_bool',
    'empty_array',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  const msg: Partial<AllZeroValues> = {};

  // Decode fields

  if ('zero_int' in obj) {
    const value = obj['zero_int'];
    msg.zeroInt = parseBigIntFromJSON(value);
  }

  if ('zero_string' in obj) {
    const value = obj['zero_string'];
    msg.zeroString = String(value);
  }

  if ('zero_bool' in obj) {
    const value = obj['zero_bool'];
    msg.zeroBool = Boolean(value);
  }

  if ('empty_array' in obj) {
    const value = obj['empty_array'];
    if (!Array.isArray(value)) throw new Error('expected array');
    msg.emptyArray = [];
    for (const elem of value) {
      let decoded: string;
      decoded = String(elem);
      msg.emptyArray.push(decoded);
    }
  }


  return msg as AllZeroValues;
}



