run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive
    - exportloopref
    - prealloc

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/cramberry/cramberry-go

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint
      - hugeParam  # Allow large struct parameters for API clarity

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  misspell:
    locale: US

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

issues:
  exclude-rules:
    # Ignore long lines in generated files
    - path: _gen\.go
      linters:
        - lll

    # Ignore test helper functions
    - path: _test\.go
      linters:
        - unparam
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0
