// Code generated by cramberry. DO NOT EDIT.
// Source: /Volumes/Tendermint/stealth/cramberry/testdata/schemas/interop.cram

import {
  Writer,
  Reader,
  WireType,
  formatBigIntToString,
  formatNumberToString,
  formatFloat32,
  formatFloat64,
  encodeBase64,
  decodeBase64,
  parseBigIntFromJSON,
  parseNumberFromJSON,
  sortMapKeysLexicographic,
  escapeJSONString,
} from '@cramberry/runtime';
import type { ReaderOptions } from '@cramberry/runtime';

// Helper functions for encoding/decoding
function writeArray<T>(writer: Writer, arr: T[], writeElem: (w: Writer, v: T) => void): void {
  const cp = writer.beginMessage();
  writer.writeVarint(arr.length);
  for (const elem of arr) {
    writeElem(writer, elem);
  }
  writer.endMessage(cp);
}

function readArray<T>(reader: Reader, readElem: (r: Reader) => T): T[] {
  const data = reader.readLengthPrefixedBytes();
  const subReader = new Reader(data, { limits: reader.getLimits(), validateUtf8: reader.getValidateUtf8() });
  const len = subReader.readVarint();
  subReader.checkArrayLimit(len);
  const result: T[] = [];
  for (let i = 0; i < len; i++) {
    result.push(readElem(subReader));
  }
  return result;
}

// compareMapKeys provides the canonical map-key ordering used on the wire.
// String keys compare by UTF-8 byte order (matching Go's sort.Strings).
// Numeric keys compare numerically with NaN sorted last and -0 == +0.
// BigInt keys compare numerically. Boolean keys order false before true.
const __mapKeyEncoder = new TextEncoder();
function compareMapKeys(a: unknown, b: unknown): number {
  if (typeof a === 'string' && typeof b === 'string') {
    const ab = __mapKeyEncoder.encode(a);
    const bb = __mapKeyEncoder.encode(b);
    const n = Math.min(ab.length, bb.length);
    for (let i = 0; i < n; i++) if (ab[i] !== bb[i]) return ab[i] - bb[i];
    return ab.length - bb.length;
  }
  if (typeof a === 'number' && typeof b === 'number') {
    const aNaN = Number.isNaN(a), bNaN = Number.isNaN(b);
    if (aNaN && bNaN) return 0; // payloads are not observable in JS
    if (aNaN) return 1;
    if (bNaN) return -1;
    return a < b ? -1 : a > b ? 1 : 0; // -0 and +0 compare equal here
  }
  if (typeof a === 'bigint' && typeof b === 'bigint') {
    return a < b ? -1 : a > b ? 1 : 0;
  }
  if (typeof a === 'boolean' && typeof b === 'boolean') {
    return a === b ? 0 : a ? 1 : -1;
  }
  // Mixed types: fall back to string comparison so the ordering is at least
  // total, even if the schema validator should have rejected this.
  return String(a) < String(b) ? -1 : String(a) > String(b) ? 1 : 0;
}

function writeMap<K, V>(writer: Writer, map: Map<K, V> | Record<string, V>, writeKey: (w: Writer, k: K) => void, writeVal: (w: Writer, v: V) => void): void {
  const cp = writer.beginMessage();
  const entries = map instanceof Map ? Array.from(map.entries()) : Object.entries(map);
  // Sort by key for deterministic output. Map iteration order is
  // implementation-defined and varies per insertion order; the wire format
  // requires a canonical order matching the Go reflection marshaller.
  entries.sort((a, b) => compareMapKeys(a[0], b[0]));
  writer.writeVarint(entries.length);
  for (const [k, v] of entries) {
    writeKey(writer, k as K);
    writeVal(writer, v as V);
  }
  writer.endMessage(cp);
}

function readMap<K, V>(reader: Reader, readKey: (r: Reader) => K, readVal: (r: Reader) => V): Map<K, V> {
  const data = reader.readLengthPrefixedBytes();
  const subReader = new Reader(data, { limits: reader.getLimits(), validateUtf8: reader.getValidateUtf8() });
  const len = subReader.readVarint();
  subReader.checkMapLimit(len);
  const result = new Map<K, V>();
  for (let i = 0; i < len; i++) {
    const k = readKey(subReader);
    const v = readVal(subReader);
    result.set(k, v);
  }
  return result;
}



/** Status enum for testing enum serialization. */
export enum Status {
Unknown = 0,
Active = 1,
Inactive = 2,
Pending = 3,
}



/** ScalarTypes tests all scalar type serialization. */
export interface ScalarTypes {
boolVal: boolean;
int32Val: number;
int64Val: bigint;
uint32Val: number;
uint64Val: bigint;
float32Val: number;
float64Val: number;
stringVal: string;
bytesVal: Uint8Array;
}

/** Encodes a ScalarTypes to the writer. */
export function encodeScalarTypes(writer: Writer, msg: ScalarTypes): void {

  // Field 1: bool_val
  if (msg.boolVal !== undefined && msg.boolVal !== null && msg.boolVal) {
    writer.writeTag(1, WireType.Varint);
    writer.writeBool(msg.boolVal);
  }

  // Field 2: int32_val
  if (msg.int32Val !== undefined && msg.int32Val !== null && msg.int32Val !== 0) {
    writer.writeTag(2, WireType.SVarint);
    writer.writeSVarint(msg.int32Val);
  }

  // Field 3: int64_val
  if (msg.int64Val !== undefined && msg.int64Val !== null && msg.int64Val !== 0n) {
    writer.writeTag(3, WireType.SVarint);
    writer.writeSVarint64(msg.int64Val);
  }

  // Field 4: uint32_val
  if (msg.uint32Val !== undefined && msg.uint32Val !== null && msg.uint32Val !== 0) {
    writer.writeTag(4, WireType.Varint);
    writer.writeVarint(msg.uint32Val);
  }

  // Field 5: uint64_val
  if (msg.uint64Val !== undefined && msg.uint64Val !== null && msg.uint64Val !== 0n) {
    writer.writeTag(5, WireType.Varint);
    writer.writeVarint64(msg.uint64Val);
  }

  // Field 6: float32_val
  if (msg.float32Val !== undefined && msg.float32Val !== null && msg.float32Val !== 0) {
    writer.writeTag(6, WireType.Fixed32);
    writer.writeFloat32(msg.float32Val);
  }

  // Field 7: float64_val
  if (msg.float64Val !== undefined && msg.float64Val !== null && msg.float64Val !== 0) {
    writer.writeTag(7, WireType.Fixed64);
    writer.writeFloat64(msg.float64Val);
  }

  // Field 8: string_val
  if (msg.stringVal !== undefined && msg.stringVal !== null && msg.stringVal.length > 0) {
    writer.writeTag(8, WireType.Bytes);
    writer.writeString(msg.stringVal);
  }

  // Field 9: bytes_val
  if (msg.bytesVal !== undefined && msg.bytesVal !== null && msg.bytesVal.length > 0) {
    writer.writeTag(9, WireType.Bytes);
    writer.writeLengthPrefixedBytes(msg.bytesVal);
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a ScalarTypes from the reader. */
export function decodeScalarTypes(reader: Reader): ScalarTypes {
  // Initialize all fields up front so V8 builds a single stable
  // hidden class. The previous Partial-and-fill pattern produced a
  // different hidden-class transition tree per input ordering, which
  // deopted downstream consumers.
  const result: ScalarTypes = {
    boolVal: false,
    int32Val: 0,
    int64Val: 0n,
    uint32Val: 0,
    uint64Val: 0n,
    float32Val: 0,
    float64Val: 0,
    stringVal: '',
    bytesVal: new Uint8Array(0),
  };

  while (true) {
    const { fieldNumber, wireType } = reader.readTag();
    if (fieldNumber === 0) break; // End marker

    switch (fieldNumber) {
      case 1:
        result.boolVal = reader.readBool();
        break;
      case 2:
        result.int32Val = reader.readSVarint();
        break;
      case 3:
        result.int64Val = reader.readSVarint64();
        break;
      case 4:
        result.uint32Val = reader.readVarint();
        break;
      case 5:
        result.uint64Val = reader.readVarint64();
        break;
      case 6:
        result.float32Val = reader.readFloat32();
        break;
      case 7:
        result.float64Val = reader.readFloat64();
        break;
      case 8:
        result.stringVal = reader.readString();
        break;
      case 9:
        result.bytesVal = reader.readLengthPrefixedBytes();
        break;
      default:
        reader.skipValue(wireType);
    }
  }

  return result;
}

/** Marshals a ScalarTypes to bytes. */
export function marshalScalarTypes(msg: ScalarTypes): Uint8Array {
  const writer = new Writer();
  encodeScalarTypes(writer, msg);
  return writer.bytes();
}

/** Unmarshals a ScalarTypes from bytes. */
export function unmarshalScalarTypes(data: Uint8Array, opts?: ReaderOptions): ScalarTypes {
  const reader = new Reader(data, opts);
  return decodeScalarTypes(reader);
}

/** Encodes a ScalarTypes to deterministic JSON format. */
export function toJSON_ScalarTypes(msg: ScalarTypes): string {
  let result = '{';

  result += '"bool_val":';
  result += msg.boolVal ? 'true' : 'false';

  result += ',';
  result += '"int32_val":';
  result += '"' + formatNumberToString(msg.int32Val) + '"';

  result += ',';
  result += '"int64_val":';
  result += '"' + formatBigIntToString(msg.int64Val) + '"';

  result += ',';
  result += '"uint32_val":';
  result += '"' + formatNumberToString(msg.uint32Val) + '"';

  result += ',';
  result += '"uint64_val":';
  result += '"' + formatBigIntToString(msg.uint64Val) + '"';

  result += ',';
  result += '"float32_val":';
  result += formatFloat32(msg.float32Val);

  result += ',';
  result += '"float64_val":';
  result += formatFloat64(msg.float64Val);

  result += ',';
  result += '"string_val":';
  result += escapeJSONString(msg.stringVal);

  result += ',';
  result += '"bytes_val":';
  result += '"' + encodeBase64(msg.bytesVal) + '"';

  result += '}';
  return result;
}

/** Decodes a ScalarTypes from JSON format. */
export function fromJSON_ScalarTypes(json: string): ScalarTypes {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode). Explicit string type
  // arg keeps tsc --strict happy when the message has zero fields
  // (otherwise the empty array literal infers as never[]).
  const allowedFields = new Set<string>([
    'bool_val',
    'int32_val',
    'int64_val',
    'uint32_val',
    'uint64_val',
    'float32_val',
    'float64_val',
    'string_val',
    'bytes_val',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  // Initialize with defaults for V8 hidden-class stability (see decode helper).
  const msg: ScalarTypes = {
    boolVal: false,
    int32Val: 0,
    int64Val: 0n,
    uint32Val: 0,
    uint64Val: 0n,
    float32Val: 0,
    float64Val: 0,
    stringVal: '',
    bytesVal: new Uint8Array(0),
  };

  // Decode fields

  if ('bool_val' in obj) {
    const value = obj['bool_val'];
    msg.boolVal = Boolean(value);
  }

  if ('int32_val' in obj) {
    const value = obj['int32_val'];
    msg.int32Val = parseNumberFromJSON(value as string | number);
  }

  if ('int64_val' in obj) {
    const value = obj['int64_val'];
    msg.int64Val = parseBigIntFromJSON(value as string | number);
  }

  if ('uint32_val' in obj) {
    const value = obj['uint32_val'];
    msg.uint32Val = parseNumberFromJSON(value as string | number);
  }

  if ('uint64_val' in obj) {
    const value = obj['uint64_val'];
    msg.uint64Val = parseBigIntFromJSON(value as string | number);
  }

  if ('float32_val' in obj) {
    const value = obj['float32_val'];
    msg.float32Val = Number(value);
  }

  if ('float64_val' in obj) {
    const value = obj['float64_val'];
    msg.float64Val = Number(value);
  }

  if ('string_val' in obj) {
    const value = obj['string_val'];
    msg.stringVal = String(value);
  }

  if ('bytes_val' in obj) {
    const value = obj['bytes_val'];
    msg.bytesVal = decodeBase64(String(value));
  }


  return msg;
}


/** RepeatedTypes tests repeated field serialization. */
export interface RepeatedTypes {
int32List: number[];
stringList: string[];
bytesList: Uint8Array[];
}

/** Encodes a RepeatedTypes to the writer. */
export function encodeRepeatedTypes(writer: Writer, msg: RepeatedTypes): void {

  // Field 1: int32_list
  if (msg.int32List !== undefined && msg.int32List !== null && msg.int32List.length > 0) {
    writer.writeTag(1, WireType.Bytes);
    writeArray(writer, msg.int32List, (w, v) => { w.writeSVarint(v) });
  }

  // Field 2: string_list
  if (msg.stringList !== undefined && msg.stringList !== null && msg.stringList.length > 0) {
    writer.writeTag(2, WireType.Bytes);
    writeArray(writer, msg.stringList, (w, v) => { w.writeString(v) });
  }

  // Field 3: bytes_list
  if (msg.bytesList !== undefined && msg.bytesList !== null && msg.bytesList.length > 0) {
    writer.writeTag(3, WireType.Bytes);
    writeArray(writer, msg.bytesList, (w, v) => { w.writeLengthPrefixedBytes(v) });
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a RepeatedTypes from the reader. */
export function decodeRepeatedTypes(reader: Reader): RepeatedTypes {
  // Initialize all fields up front so V8 builds a single stable
  // hidden class. The previous Partial-and-fill pattern produced a
  // different hidden-class transition tree per input ordering, which
  // deopted downstream consumers.
  const result: RepeatedTypes = {
    int32List: [],
    stringList: [],
    bytesList: [],
  };

  while (true) {
    const { fieldNumber, wireType } = reader.readTag();
    if (fieldNumber === 0) break; // End marker

    switch (fieldNumber) {
      case 1:
        result.int32List = readArray(reader, (r) => r.readSVarint());
        break;
      case 2:
        result.stringList = readArray(reader, (r) => r.readString());
        break;
      case 3:
        result.bytesList = readArray(reader, (r) => r.readLengthPrefixedBytes());
        break;
      default:
        reader.skipValue(wireType);
    }
  }

  return result;
}

/** Marshals a RepeatedTypes to bytes. */
export function marshalRepeatedTypes(msg: RepeatedTypes): Uint8Array {
  const writer = new Writer();
  encodeRepeatedTypes(writer, msg);
  return writer.bytes();
}

/** Unmarshals a RepeatedTypes from bytes. */
export function unmarshalRepeatedTypes(data: Uint8Array, opts?: ReaderOptions): RepeatedTypes {
  const reader = new Reader(data, opts);
  return decodeRepeatedTypes(reader);
}

/** Encodes a RepeatedTypes to deterministic JSON format. */
export function toJSON_RepeatedTypes(msg: RepeatedTypes): string {
  let result = '{';

  result += '"int32_list":';
  result += '[';
  for (let i = 0; i < msg.int32List.length; i++) {
    if (i > 0) result += ',';
    const elem = msg.int32List[i];
    result += '"' + formatNumberToString(elem) + '"';
  }
  result += ']';

  result += ',';
  result += '"string_list":';
  result += '[';
  for (let i = 0; i < msg.stringList.length; i++) {
    if (i > 0) result += ',';
    const elem = msg.stringList[i];
    result += escapeJSONString(elem);
  }
  result += ']';

  result += ',';
  result += '"bytes_list":';
  result += '[';
  for (let i = 0; i < msg.bytesList.length; i++) {
    if (i > 0) result += ',';
    const elem = msg.bytesList[i];
    result += '"' + encodeBase64(elem) + '"';
  }
  result += ']';

  result += '}';
  return result;
}

/** Decodes a RepeatedTypes from JSON format. */
export function fromJSON_RepeatedTypes(json: string): RepeatedTypes {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode). Explicit string type
  // arg keeps tsc --strict happy when the message has zero fields
  // (otherwise the empty array literal infers as never[]).
  const allowedFields = new Set<string>([
    'int32_list',
    'string_list',
    'bytes_list',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  // Initialize with defaults for V8 hidden-class stability (see decode helper).
  const msg: RepeatedTypes = {
    int32List: [],
    stringList: [],
    bytesList: [],
  };

  // Decode fields

  if ('int32_list' in obj) {
    const value = obj['int32_list'];
    if (!Array.isArray(value)) throw new Error('expected array');
    msg.int32List = [];
    for (const elem of value) {
      let decoded: number;
      decoded = parseNumberFromJSON(elem as string | number);
      msg.int32List.push(decoded);
    }
  }

  if ('string_list' in obj) {
    const value = obj['string_list'];
    if (!Array.isArray(value)) throw new Error('expected array');
    msg.stringList = [];
    for (const elem of value) {
      let decoded: string;
      decoded = String(elem);
      msg.stringList.push(decoded);
    }
  }

  if ('bytes_list' in obj) {
    const value = obj['bytes_list'];
    if (!Array.isArray(value)) throw new Error('expected array');
    msg.bytesList = [];
    for (const elem of value) {
      let decoded: Uint8Array;
      decoded = decodeBase64(String(elem));
      msg.bytesList.push(decoded);
    }
  }


  return msg;
}


/** NestedMessage tests nested message serialization. */
export interface NestedMessage {
name: string;
value: number;
}

/** Encodes a NestedMessage to the writer. */
export function encodeNestedMessage(writer: Writer, msg: NestedMessage): void {

  // Field 1: name
  if (msg.name !== undefined && msg.name !== null && msg.name.length > 0) {
    writer.writeTag(1, WireType.Bytes);
    writer.writeString(msg.name);
  }

  // Field 2: value
  if (msg.value !== undefined && msg.value !== null && msg.value !== 0) {
    writer.writeTag(2, WireType.SVarint);
    writer.writeSVarint(msg.value);
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a NestedMessage from the reader. */
export function decodeNestedMessage(reader: Reader): NestedMessage {
  // Initialize all fields up front so V8 builds a single stable
  // hidden class. The previous Partial-and-fill pattern produced a
  // different hidden-class transition tree per input ordering, which
  // deopted downstream consumers.
  const result: NestedMessage = {
    name: '',
    value: 0,
  };

  while (true) {
    const { fieldNumber, wireType } = reader.readTag();
    if (fieldNumber === 0) break; // End marker

    switch (fieldNumber) {
      case 1:
        result.name = reader.readString();
        break;
      case 2:
        result.value = reader.readSVarint();
        break;
      default:
        reader.skipValue(wireType);
    }
  }

  return result;
}

/** Marshals a NestedMessage to bytes. */
export function marshalNestedMessage(msg: NestedMessage): Uint8Array {
  const writer = new Writer();
  encodeNestedMessage(writer, msg);
  return writer.bytes();
}

/** Unmarshals a NestedMessage from bytes. */
export function unmarshalNestedMessage(data: Uint8Array, opts?: ReaderOptions): NestedMessage {
  const reader = new Reader(data, opts);
  return decodeNestedMessage(reader);
}

/** Encodes a NestedMessage to deterministic JSON format. */
export function toJSON_NestedMessage(msg: NestedMessage): string {
  let result = '{';

  result += '"name":';
  result += escapeJSONString(msg.name);

  result += ',';
  result += '"value":';
  result += '"' + formatNumberToString(msg.value) + '"';

  result += '}';
  return result;
}

/** Decodes a NestedMessage from JSON format. */
export function fromJSON_NestedMessage(json: string): NestedMessage {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode). Explicit string type
  // arg keeps tsc --strict happy when the message has zero fields
  // (otherwise the empty array literal infers as never[]).
  const allowedFields = new Set<string>([
    'name',
    'value',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  // Initialize with defaults for V8 hidden-class stability (see decode helper).
  const msg: NestedMessage = {
    name: '',
    value: 0,
  };

  // Decode fields

  if ('name' in obj) {
    const value = obj['name'];
    msg.name = String(value);
  }

  if ('value' in obj) {
    const value = obj['value'];
    msg.value = parseNumberFromJSON(value as string | number);
  }


  return msg;
}


/** ComplexTypes tests complex type serialization. */
export interface ComplexTypes {
status: Status;
optionalNested: NestedMessage | null;
requiredNested: NestedMessage;
nestedList: NestedMessage[];
stringIntMap: Map<string, number>;
intStringMap: Map<number, string>;
}

/** Encodes a ComplexTypes to the writer. */
export function encodeComplexTypes(writer: Writer, msg: ComplexTypes): void {

  // Field 1: status
  writer.writeTag(1, WireType.SVarint);
  writer.writeSVarint(msg.status);

  // Field 2: optional_nested
  if (msg.optionalNested !== undefined && msg.optionalNested !== null) {
    writer.writeTag(2, WireType.Bytes);
    if (msg.optionalNested !== null) { { const __cp = writer.beginMessage(); encodeNestedMessage(writer, msg.optionalNested); writer.endMessage(__cp); } };
  }

  // Field 3: required_nested
  writer.writeTag(3, WireType.Bytes);
  { const __cp = writer.beginMessage(); encodeNestedMessage(writer, msg.requiredNested); writer.endMessage(__cp); };

  // Field 4: nested_list
  if (msg.nestedList !== undefined && msg.nestedList !== null && msg.nestedList.length > 0) {
    writer.writeTag(4, WireType.Bytes);
    writeArray(writer, msg.nestedList, (w, v) => { encodeNestedMessage(w, v) });
  }

  // Field 5: string_int_map
  writer.writeTag(5, WireType.Bytes);
  writeMap(writer, msg.stringIntMap, (w, k) => { w.writeString(k) }, (w, v) => { w.writeSVarint(v) });

  // Field 6: int_string_map
  writer.writeTag(6, WireType.Bytes);
  writeMap(writer, msg.intStringMap, (w, k) => { w.writeSVarint(k) }, (w, v) => { w.writeString(v) });
// End marker
  writer.writeEndMarker();
}

/** Decodes a ComplexTypes from the reader. */
export function decodeComplexTypes(reader: Reader): ComplexTypes {
  // Initialize all fields up front so V8 builds a single stable
  // hidden class. The previous Partial-and-fill pattern produced a
  // different hidden-class transition tree per input ordering, which
  // deopted downstream consumers.
  const result: ComplexTypes = {
    status: 0 as Status,
    optionalNested: null,
    requiredNested: ({} as NestedMessage),
    nestedList: [],
    stringIntMap: new Map(),
    intStringMap: new Map(),
  };

  while (true) {
    const { fieldNumber, wireType } = reader.readTag();
    if (fieldNumber === 0) break; // End marker

    switch (fieldNumber) {
      case 1:
        result.status = reader.readSVarint();
        break;
      case 2:
        result.optionalNested = (() => { reader.enterNested(); try { const __data = reader.readLengthPrefixedBytes(); return decodeNestedMessage(new Reader(__data, { limits: reader.getLimits(), validateUtf8: reader.getValidateUtf8() })); } finally { reader.exitNested(); } })();
        break;
      case 3:
        result.requiredNested = (() => { reader.enterNested(); try { const __data = reader.readLengthPrefixedBytes(); return decodeNestedMessage(new Reader(__data, { limits: reader.getLimits(), validateUtf8: reader.getValidateUtf8() })); } finally { reader.exitNested(); } })();
        break;
      case 4:
        result.nestedList = readArray(reader, (r) => decodeNestedMessage(r));
        break;
      case 5:
        result.stringIntMap = readMap(reader, (r) => r.readString(), (r) => r.readSVarint());
        break;
      case 6:
        result.intStringMap = readMap(reader, (r) => r.readSVarint(), (r) => r.readString());
        break;
      default:
        reader.skipValue(wireType);
    }
  }

  return result;
}

/** Marshals a ComplexTypes to bytes. */
export function marshalComplexTypes(msg: ComplexTypes): Uint8Array {
  const writer = new Writer();
  encodeComplexTypes(writer, msg);
  return writer.bytes();
}

/** Unmarshals a ComplexTypes from bytes. */
export function unmarshalComplexTypes(data: Uint8Array, opts?: ReaderOptions): ComplexTypes {
  const reader = new Reader(data, opts);
  return decodeComplexTypes(reader);
}

/** Encodes a ComplexTypes to deterministic JSON format. */
export function toJSON_ComplexTypes(msg: ComplexTypes): string {
  let result = '{';

  result += '"status":';
  result += '"' + (() => { switch (msg.status) {
    case Status.Unknown: return "UNKNOWN";
    case Status.Active: return "ACTIVE";
    case Status.Inactive: return "INACTIVE";
    case Status.Pending: return "PENDING";
    default: return 'UNKNOWN';
  } })() + '"';

  result += ',';
  result += '"optional_nested":';
  if (msg.optionalNested != null) {
      result += toJSON_NestedMessage(msg.optionalNested);
  } else {
    result += 'null';
  }

  result += ',';
  result += '"required_nested":';
  result += toJSON_NestedMessage(msg.requiredNested);

  result += ',';
  result += '"nested_list":';
  result += '[';
  for (let i = 0; i < msg.nestedList.length; i++) {
    if (i > 0) result += ',';
    const elem = msg.nestedList[i];
    result += toJSON_NestedMessage(elem);
  }
  result += ']';

  result += ',';
  result += '"string_int_map":';
  {
    result += '{';
    const keys = Array.from(msg.stringIntMap.keys());
    const sortedKeys = sortMapKeysLexicographic(keys);
    for (let i = 0; i < sortedKeys.length; i++) {
      if (i > 0) result += ',';
      result += escapeJSONString(sortedKeys[i]) + ':';
      const k = sortedKeys[i];
      const v = msg.stringIntMap.get(k)!;
      result += '"' + formatNumberToString(v) + '"';
    }
    result += '}';
  }

  result += ',';
  result += '"int_string_map":';
  {
    result += '{';
    const keys = Array.from(msg.intStringMap.keys());
    const sortedKeys = sortMapKeysLexicographic(keys.map(k => formatNumberToString(k)));
    for (let i = 0; i < sortedKeys.length; i++) {
      if (i > 0) result += ',';
      result += escapeJSONString(sortedKeys[i]) + ':';
      const k = parseNumberFromJSON(sortedKeys[i]);
      const v = msg.intStringMap.get(k)!;
      result += escapeJSONString(v);
    }
    result += '}';
  }

  result += '}';
  return result;
}

/** Decodes a ComplexTypes from JSON format. */
export function fromJSON_ComplexTypes(json: string): ComplexTypes {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode). Explicit string type
  // arg keeps tsc --strict happy when the message has zero fields
  // (otherwise the empty array literal infers as never[]).
  const allowedFields = new Set<string>([
    'status',
    'optional_nested',
    'required_nested',
    'nested_list',
    'string_int_map',
    'int_string_map',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  // Initialize with defaults for V8 hidden-class stability (see decode helper).
  const msg: ComplexTypes = {
    status: 0 as Status,
    optionalNested: null,
    requiredNested: ({} as NestedMessage),
    nestedList: [],
    stringIntMap: new Map(),
    intStringMap: new Map(),
  };

  // Decode fields

  if ('status' in obj) {
    const value = obj['status'];
    const strVal = String(value);
    switch (strVal) {
      case 'UNKNOWN':
        msg.status = Status.Unknown;
        break;
      case 'ACTIVE':
        msg.status = Status.Active;
        break;
      case 'INACTIVE':
        msg.status = Status.Inactive;
        break;
      case 'PENDING':
        msg.status = Status.Pending;
        break;
      default:
        throw new Error(`unknown enum value: ${strVal}`);
    }
  }

  if ('optional_nested' in obj) {
    const value = obj['optional_nested'];
    if (value != null) {
      msg.optionalNested = fromJSON_NestedMessage(JSON.stringify(value));
    } else {
      msg.optionalNested = null;
    }
  }

  if ('required_nested' in obj) {
    const value = obj['required_nested'];
    msg.requiredNested = fromJSON_NestedMessage(JSON.stringify(value));
  }

  if ('nested_list' in obj) {
    const value = obj['nested_list'];
    if (!Array.isArray(value)) throw new Error('expected array');
    msg.nestedList = [];
    for (const elem of value) {
      let decoded: NestedMessage;
      decoded = fromJSON_NestedMessage(JSON.stringify(elem));
      msg.nestedList.push(decoded);
    }
  }

  if ('string_int_map' in obj) {
    const value = obj['string_int_map'];
    if (typeof value !== 'object' || value === null) throw new Error('expected object');
    msg.stringIntMap = new Map();
    for (const [keyStr, val] of Object.entries(value)) {
      const k = keyStr;
      let v: number;
      v = parseNumberFromJSON(val as string | number);
      msg.stringIntMap.set(k, v);
    }
  }

  if ('int_string_map' in obj) {
    const value = obj['int_string_map'];
    if (typeof value !== 'object' || value === null) throw new Error('expected object');
    msg.intStringMap = new Map();
    for (const [keyStr, val] of Object.entries(value)) {
      const k = parseNumberFromJSON(keyStr);
      let v: string;
      v = String(val);
      msg.intStringMap.set(k, v);
    }
  }


  return msg;
}


/** EdgeCases tests edge case values. */
export interface EdgeCases {
zeroInt: number;
negativeOne: number;
maxInt32: number;
minInt32: number;
maxInt64: bigint;
minInt64: bigint;
maxUint32: number;
maxUint64: bigint;
emptyString: string;
unicodeString: string;
emptyBytes: Uint8Array;
}

/** Encodes a EdgeCases to the writer. */
export function encodeEdgeCases(writer: Writer, msg: EdgeCases): void {

  // Field 1: zero_int
  if (msg.zeroInt !== undefined && msg.zeroInt !== null && msg.zeroInt !== 0) {
    writer.writeTag(1, WireType.SVarint);
    writer.writeSVarint(msg.zeroInt);
  }

  // Field 2: negative_one
  if (msg.negativeOne !== undefined && msg.negativeOne !== null && msg.negativeOne !== 0) {
    writer.writeTag(2, WireType.SVarint);
    writer.writeSVarint(msg.negativeOne);
  }

  // Field 3: max_int32
  if (msg.maxInt32 !== undefined && msg.maxInt32 !== null && msg.maxInt32 !== 0) {
    writer.writeTag(3, WireType.SVarint);
    writer.writeSVarint(msg.maxInt32);
  }

  // Field 4: min_int32
  if (msg.minInt32 !== undefined && msg.minInt32 !== null && msg.minInt32 !== 0) {
    writer.writeTag(4, WireType.SVarint);
    writer.writeSVarint(msg.minInt32);
  }

  // Field 5: max_int64
  if (msg.maxInt64 !== undefined && msg.maxInt64 !== null && msg.maxInt64 !== 0n) {
    writer.writeTag(5, WireType.SVarint);
    writer.writeSVarint64(msg.maxInt64);
  }

  // Field 6: min_int64
  if (msg.minInt64 !== undefined && msg.minInt64 !== null && msg.minInt64 !== 0n) {
    writer.writeTag(6, WireType.SVarint);
    writer.writeSVarint64(msg.minInt64);
  }

  // Field 7: max_uint32
  if (msg.maxUint32 !== undefined && msg.maxUint32 !== null && msg.maxUint32 !== 0) {
    writer.writeTag(7, WireType.Varint);
    writer.writeVarint(msg.maxUint32);
  }

  // Field 8: max_uint64
  if (msg.maxUint64 !== undefined && msg.maxUint64 !== null && msg.maxUint64 !== 0n) {
    writer.writeTag(8, WireType.Varint);
    writer.writeVarint64(msg.maxUint64);
  }

  // Field 9: empty_string
  if (msg.emptyString !== undefined && msg.emptyString !== null && msg.emptyString.length > 0) {
    writer.writeTag(9, WireType.Bytes);
    writer.writeString(msg.emptyString);
  }

  // Field 10: unicode_string
  if (msg.unicodeString !== undefined && msg.unicodeString !== null && msg.unicodeString.length > 0) {
    writer.writeTag(10, WireType.Bytes);
    writer.writeString(msg.unicodeString);
  }

  // Field 11: empty_bytes
  if (msg.emptyBytes !== undefined && msg.emptyBytes !== null && msg.emptyBytes.length > 0) {
    writer.writeTag(11, WireType.Bytes);
    writer.writeLengthPrefixedBytes(msg.emptyBytes);
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a EdgeCases from the reader. */
export function decodeEdgeCases(reader: Reader): EdgeCases {
  // Initialize all fields up front so V8 builds a single stable
  // hidden class. The previous Partial-and-fill pattern produced a
  // different hidden-class transition tree per input ordering, which
  // deopted downstream consumers.
  const result: EdgeCases = {
    zeroInt: 0,
    negativeOne: 0,
    maxInt32: 0,
    minInt32: 0,
    maxInt64: 0n,
    minInt64: 0n,
    maxUint32: 0,
    maxUint64: 0n,
    emptyString: '',
    unicodeString: '',
    emptyBytes: new Uint8Array(0),
  };

  while (true) {
    const { fieldNumber, wireType } = reader.readTag();
    if (fieldNumber === 0) break; // End marker

    switch (fieldNumber) {
      case 1:
        result.zeroInt = reader.readSVarint();
        break;
      case 2:
        result.negativeOne = reader.readSVarint();
        break;
      case 3:
        result.maxInt32 = reader.readSVarint();
        break;
      case 4:
        result.minInt32 = reader.readSVarint();
        break;
      case 5:
        result.maxInt64 = reader.readSVarint64();
        break;
      case 6:
        result.minInt64 = reader.readSVarint64();
        break;
      case 7:
        result.maxUint32 = reader.readVarint();
        break;
      case 8:
        result.maxUint64 = reader.readVarint64();
        break;
      case 9:
        result.emptyString = reader.readString();
        break;
      case 10:
        result.unicodeString = reader.readString();
        break;
      case 11:
        result.emptyBytes = reader.readLengthPrefixedBytes();
        break;
      default:
        reader.skipValue(wireType);
    }
  }

  return result;
}

/** Marshals a EdgeCases to bytes. */
export function marshalEdgeCases(msg: EdgeCases): Uint8Array {
  const writer = new Writer();
  encodeEdgeCases(writer, msg);
  return writer.bytes();
}

/** Unmarshals a EdgeCases from bytes. */
export function unmarshalEdgeCases(data: Uint8Array, opts?: ReaderOptions): EdgeCases {
  const reader = new Reader(data, opts);
  return decodeEdgeCases(reader);
}

/** Encodes a EdgeCases to deterministic JSON format. */
export function toJSON_EdgeCases(msg: EdgeCases): string {
  let result = '{';

  result += '"zero_int":';
  result += '"' + formatNumberToString(msg.zeroInt) + '"';

  result += ',';
  result += '"negative_one":';
  result += '"' + formatNumberToString(msg.negativeOne) + '"';

  result += ',';
  result += '"max_int32":';
  result += '"' + formatNumberToString(msg.maxInt32) + '"';

  result += ',';
  result += '"min_int32":';
  result += '"' + formatNumberToString(msg.minInt32) + '"';

  result += ',';
  result += '"max_int64":';
  result += '"' + formatBigIntToString(msg.maxInt64) + '"';

  result += ',';
  result += '"min_int64":';
  result += '"' + formatBigIntToString(msg.minInt64) + '"';

  result += ',';
  result += '"max_uint32":';
  result += '"' + formatNumberToString(msg.maxUint32) + '"';

  result += ',';
  result += '"max_uint64":';
  result += '"' + formatBigIntToString(msg.maxUint64) + '"';

  result += ',';
  result += '"empty_string":';
  result += escapeJSONString(msg.emptyString);

  result += ',';
  result += '"unicode_string":';
  result += escapeJSONString(msg.unicodeString);

  result += ',';
  result += '"empty_bytes":';
  result += '"' + encodeBase64(msg.emptyBytes) + '"';

  result += '}';
  return result;
}

/** Decodes a EdgeCases from JSON format. */
export function fromJSON_EdgeCases(json: string): EdgeCases {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode). Explicit string type
  // arg keeps tsc --strict happy when the message has zero fields
  // (otherwise the empty array literal infers as never[]).
  const allowedFields = new Set<string>([
    'zero_int',
    'negative_one',
    'max_int32',
    'min_int32',
    'max_int64',
    'min_int64',
    'max_uint32',
    'max_uint64',
    'empty_string',
    'unicode_string',
    'empty_bytes',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  // Initialize with defaults for V8 hidden-class stability (see decode helper).
  const msg: EdgeCases = {
    zeroInt: 0,
    negativeOne: 0,
    maxInt32: 0,
    minInt32: 0,
    maxInt64: 0n,
    minInt64: 0n,
    maxUint32: 0,
    maxUint64: 0n,
    emptyString: '',
    unicodeString: '',
    emptyBytes: new Uint8Array(0),
  };

  // Decode fields

  if ('zero_int' in obj) {
    const value = obj['zero_int'];
    msg.zeroInt = parseNumberFromJSON(value as string | number);
  }

  if ('negative_one' in obj) {
    const value = obj['negative_one'];
    msg.negativeOne = parseNumberFromJSON(value as string | number);
  }

  if ('max_int32' in obj) {
    const value = obj['max_int32'];
    msg.maxInt32 = parseNumberFromJSON(value as string | number);
  }

  if ('min_int32' in obj) {
    const value = obj['min_int32'];
    msg.minInt32 = parseNumberFromJSON(value as string | number);
  }

  if ('max_int64' in obj) {
    const value = obj['max_int64'];
    msg.maxInt64 = parseBigIntFromJSON(value as string | number);
  }

  if ('min_int64' in obj) {
    const value = obj['min_int64'];
    msg.minInt64 = parseBigIntFromJSON(value as string | number);
  }

  if ('max_uint32' in obj) {
    const value = obj['max_uint32'];
    msg.maxUint32 = parseNumberFromJSON(value as string | number);
  }

  if ('max_uint64' in obj) {
    const value = obj['max_uint64'];
    msg.maxUint64 = parseBigIntFromJSON(value as string | number);
  }

  if ('empty_string' in obj) {
    const value = obj['empty_string'];
    msg.emptyString = String(value);
  }

  if ('unicode_string' in obj) {
    const value = obj['unicode_string'];
    msg.unicodeString = String(value);
  }

  if ('empty_bytes' in obj) {
    const value = obj['empty_bytes'];
    msg.emptyBytes = decodeBase64(String(value));
  }


  return msg;
}


/** AllFieldNumbers tests various field numbers including large ones. */
export interface AllFieldNumbers {
field1: number;
field15: number;
field16: number;
field127: number;
field128: number;
field1000: number;
}

/** Encodes a AllFieldNumbers to the writer. */
export function encodeAllFieldNumbers(writer: Writer, msg: AllFieldNumbers): void {

  // Field 1: field_1
  if (msg.field1 !== undefined && msg.field1 !== null && msg.field1 !== 0) {
    writer.writeTag(1, WireType.SVarint);
    writer.writeSVarint(msg.field1);
  }

  // Field 15: field_15
  if (msg.field15 !== undefined && msg.field15 !== null && msg.field15 !== 0) {
    writer.writeTag(15, WireType.SVarint);
    writer.writeSVarint(msg.field15);
  }

  // Field 16: field_16
  if (msg.field16 !== undefined && msg.field16 !== null && msg.field16 !== 0) {
    writer.writeTag(16, WireType.SVarint);
    writer.writeSVarint(msg.field16);
  }

  // Field 127: field_127
  if (msg.field127 !== undefined && msg.field127 !== null && msg.field127 !== 0) {
    writer.writeTag(127, WireType.SVarint);
    writer.writeSVarint(msg.field127);
  }

  // Field 128: field_128
  if (msg.field128 !== undefined && msg.field128 !== null && msg.field128 !== 0) {
    writer.writeTag(128, WireType.SVarint);
    writer.writeSVarint(msg.field128);
  }

  // Field 1000: field_1000
  if (msg.field1000 !== undefined && msg.field1000 !== null && msg.field1000 !== 0) {
    writer.writeTag(1000, WireType.SVarint);
    writer.writeSVarint(msg.field1000);
  }
// End marker
  writer.writeEndMarker();
}

/** Decodes a AllFieldNumbers from the reader. */
export function decodeAllFieldNumbers(reader: Reader): AllFieldNumbers {
  // Initialize all fields up front so V8 builds a single stable
  // hidden class. The previous Partial-and-fill pattern produced a
  // different hidden-class transition tree per input ordering, which
  // deopted downstream consumers.
  const result: AllFieldNumbers = {
    field1: 0,
    field15: 0,
    field16: 0,
    field127: 0,
    field128: 0,
    field1000: 0,
  };

  while (true) {
    const { fieldNumber, wireType } = reader.readTag();
    if (fieldNumber === 0) break; // End marker

    switch (fieldNumber) {
      case 1:
        result.field1 = reader.readSVarint();
        break;
      case 15:
        result.field15 = reader.readSVarint();
        break;
      case 16:
        result.field16 = reader.readSVarint();
        break;
      case 127:
        result.field127 = reader.readSVarint();
        break;
      case 128:
        result.field128 = reader.readSVarint();
        break;
      case 1000:
        result.field1000 = reader.readSVarint();
        break;
      default:
        reader.skipValue(wireType);
    }
  }

  return result;
}

/** Marshals a AllFieldNumbers to bytes. */
export function marshalAllFieldNumbers(msg: AllFieldNumbers): Uint8Array {
  const writer = new Writer();
  encodeAllFieldNumbers(writer, msg);
  return writer.bytes();
}

/** Unmarshals a AllFieldNumbers from bytes. */
export function unmarshalAllFieldNumbers(data: Uint8Array, opts?: ReaderOptions): AllFieldNumbers {
  const reader = new Reader(data, opts);
  return decodeAllFieldNumbers(reader);
}

/** Encodes a AllFieldNumbers to deterministic JSON format. */
export function toJSON_AllFieldNumbers(msg: AllFieldNumbers): string {
  let result = '{';

  result += '"field_1":';
  result += '"' + formatNumberToString(msg.field1) + '"';

  result += ',';
  result += '"field_15":';
  result += '"' + formatNumberToString(msg.field15) + '"';

  result += ',';
  result += '"field_16":';
  result += '"' + formatNumberToString(msg.field16) + '"';

  result += ',';
  result += '"field_127":';
  result += '"' + formatNumberToString(msg.field127) + '"';

  result += ',';
  result += '"field_128":';
  result += '"' + formatNumberToString(msg.field128) + '"';

  result += ',';
  result += '"field_1000":';
  result += '"' + formatNumberToString(msg.field1000) + '"';

  result += '}';
  return result;
}

/** Decodes a AllFieldNumbers from JSON format. */
export function fromJSON_AllFieldNumbers(json: string): AllFieldNumbers {
  const obj = JSON.parse(json);
  if (typeof obj !== 'object' || obj === null) {
    throw new Error('expected JSON object');
  }

  // Check for unknown fields (strict mode). Explicit string type
  // arg keeps tsc --strict happy when the message has zero fields
  // (otherwise the empty array literal infers as never[]).
  const allowedFields = new Set<string>([
    'field_1',
    'field_15',
    'field_16',
    'field_127',
    'field_128',
    'field_1000',
  ]);
  for (const key of Object.keys(obj)) {
    if (!allowedFields.has(key)) {
      throw new Error('unknown field: ' + key);
    }
  }

  // Initialize with defaults for V8 hidden-class stability (see decode helper).
  const msg: AllFieldNumbers = {
    field1: 0,
    field15: 0,
    field16: 0,
    field127: 0,
    field128: 0,
    field1000: 0,
  };

  // Decode fields

  if ('field_1' in obj) {
    const value = obj['field_1'];
    msg.field1 = parseNumberFromJSON(value as string | number);
  }

  if ('field_15' in obj) {
    const value = obj['field_15'];
    msg.field15 = parseNumberFromJSON(value as string | number);
  }

  if ('field_16' in obj) {
    const value = obj['field_16'];
    msg.field16 = parseNumberFromJSON(value as string | number);
  }

  if ('field_127' in obj) {
    const value = obj['field_127'];
    msg.field127 = parseNumberFromJSON(value as string | number);
  }

  if ('field_128' in obj) {
    const value = obj['field_128'];
    msg.field128 = parseNumberFromJSON(value as string | number);
  }

  if ('field_1000' in obj) {
    const value = obj['field_1000'];
    msg.field1000 = parseNumberFromJSON(value as string | number);
  }


  return msg;
}



