// Code generated by cramberry. DO NOT EDIT.
// Source: /Volumes/Tendermint/stealth/cramberry/testdata/schemas/json_test.cram

use serde::{Deserialize, Serialize};
use cramberry::{Reader, Result, WireType, Writer};
use serde_json;
use std::collections::HashMap;



#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[derive(Serialize, Deserialize)]
#[repr(i32)]
pub enum Status {
#[default]
Unknown = 0,
Active = 1,
Inactive = 2,
Pending = 3,
}

impl Status {
    pub fn from_i32(value: i32) -> Option<Self> {
        match value {
            0 => Some(Self::Unknown),
            1 => Some(Self::Active),
            2 => Some(Self::Inactive),
            3 => Some(Self::Pending),
            _ => None,
        }
    }

    pub fn to_string(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Active => "ACTIVE",
            Self::Inactive => "INACTIVE",
            Self::Pending => "PENDING",
        }
    }
}



#[derive(Debug, Clone, PartialEq, Default)]
#[derive(Serialize, Deserialize)]
pub struct ScalarTypes {
    #[serde(rename = "bool_val")]
    pub bool_val: bool,
    #[serde(rename = "int8_val")]
    pub int8_val: i8,
    #[serde(rename = "int16_val")]
    pub int16_val: i16,
    #[serde(rename = "int32_val")]
    pub int32_val: i32,
    #[serde(rename = "int64_val")]
    pub int64_val: i64,
    #[serde(rename = "uint8_val")]
    pub uint8_val: u8,
    #[serde(rename = "uint16_val")]
    pub uint16_val: u16,
    #[serde(rename = "uint32_val")]
    pub uint32_val: u32,
    #[serde(rename = "uint64_val")]
    pub uint64_val: u64,
    #[serde(rename = "float32_val")]
    pub float32_val: f32,
    #[serde(rename = "float64_val")]
    pub float64_val: f64,
    #[serde(rename = "string_val")]
    pub string_val: String,
    #[serde(rename = "bytes_val")]
    pub bytes_val: Vec<u8>,
}

/// Encodes a ScalarTypes to the writer.
pub fn encode_scalar_types(writer: &mut Writer, msg: &ScalarTypes) -> Result<()> {

    // Field 1: bool_val
    if msg.bool_val {
        writer.write_tag(1, WireType::Varint)?;
        writer.write_bool(msg.bool_val)?;
    }

    // Field 2: int8_val
    if msg.int8_val != 0 as i8 {
        writer.write_tag(2, WireType::SVarint)?;
        writer.write_svarint(msg.int8_val as i32)?;
    }

    // Field 3: int16_val
    if msg.int16_val != 0 as i16 {
        writer.write_tag(3, WireType::SVarint)?;
        writer.write_svarint(msg.int16_val as i32)?;
    }

    // Field 4: int32_val
    if msg.int32_val != 0 as i32 {
        writer.write_tag(4, WireType::SVarint)?;
        writer.write_svarint(msg.int32_val)?;
    }

    // Field 5: int64_val
    if msg.int64_val != 0 as i64 {
        writer.write_tag(5, WireType::SVarint)?;
        writer.write_svarint64(msg.int64_val)?;
    }

    // Field 6: uint8_val
    if msg.uint8_val != 0 as u8 {
        writer.write_tag(6, WireType::Varint)?;
        writer.write_varint(msg.uint8_val as u32)?;
    }

    // Field 7: uint16_val
    if msg.uint16_val != 0 as u16 {
        writer.write_tag(7, WireType::Varint)?;
        writer.write_varint(msg.uint16_val as u32)?;
    }

    // Field 8: uint32_val
    if msg.uint32_val != 0 as u32 {
        writer.write_tag(8, WireType::Varint)?;
        writer.write_varint(msg.uint32_val)?;
    }

    // Field 9: uint64_val
    if msg.uint64_val != 0 as u64 {
        writer.write_tag(9, WireType::Varint)?;
        writer.write_varint64(msg.uint64_val)?;
    }

    // Field 10: float32_val
    if msg.float32_val != 0 as f32 {
        writer.write_tag(10, WireType::Fixed32)?;
        writer.write_float32(msg.float32_val)?;
    }

    // Field 11: float64_val
    if msg.float64_val != 0 as f64 {
        writer.write_tag(11, WireType::Fixed64)?;
        writer.write_float64(msg.float64_val)?;
    }

    // Field 12: string_val
    if !msg.string_val.is_empty() {
        writer.write_tag(12, WireType::Bytes)?;
        writer.write_string(&msg.string_val)?;
    }

    // Field 13: bytes_val
    if !msg.bytes_val.is_empty() {
        writer.write_tag(13, WireType::Bytes)?;
        writer.write_length_prefixed_bytes(&msg.bytes_val)?;
    }

    // End marker
    writer.write_end_marker()?;
    Ok(())
}

/// Decodes a ScalarTypes from the reader.
pub fn decode_scalar_types(reader: &mut Reader) -> Result<ScalarTypes> {
    let mut bool_val: bool = Default::default();
    let mut int8_val: i8 = Default::default();
    let mut int16_val: i16 = Default::default();
    let mut int32_val: i32 = Default::default();
    let mut int64_val: i64 = Default::default();
    let mut uint8_val: u8 = Default::default();
    let mut uint16_val: u16 = Default::default();
    let mut uint32_val: u32 = Default::default();
    let mut uint64_val: u64 = Default::default();
    let mut float32_val: f32 = Default::default();
    let mut float64_val: f64 = Default::default();
    let mut string_val: String = Default::default();
    let mut bytes_val: Vec<u8> = Default::default();

    loop {
        let tag = reader.read_tag()?;
        if tag.field_number == 0 { break; } // End marker

        match tag.field_number {
            1 => bool_val = reader.read_bool()?,
            2 => int8_val = reader.read_svarint()? as i8,
            3 => int16_val = reader.read_svarint()? as i16,
            4 => int32_val = reader.read_svarint()?,
            5 => int64_val = reader.read_svarint64()?,
            6 => uint8_val = reader.read_varint()? as u8,
            7 => uint16_val = reader.read_varint()? as u16,
            8 => uint32_val = reader.read_varint()?,
            9 => uint64_val = reader.read_varint64()?,
            10 => float32_val = reader.read_float32()?,
            11 => float64_val = reader.read_float64()?,
            12 => string_val = reader.read_string()?.to_string(),
            13 => bytes_val = reader.read_length_prefixed_bytes()?.to_vec(),
            _ => reader.skip_value(tag.wire_type)?,
        }
    }

    Ok(ScalarTypes {
        bool_val,
        int8_val,
        int16_val,
        int32_val,
        int64_val,
        uint8_val,
        uint16_val,
        uint32_val,
        uint64_val,
        float32_val,
        float64_val,
        string_val,
        bytes_val,
    })
}

/// Marshals a ScalarTypes to bytes.
pub fn marshal_scalar_types(msg: &ScalarTypes) -> Result<Vec<u8>> {
    let mut writer = Writer::new();
    encode_scalar_types(&mut writer, msg)?;
    Ok(writer.into_bytes())
}

/// Unmarshals a ScalarTypes from bytes.
pub fn unmarshal_scalar_types(data: &[u8]) -> Result<ScalarTypes> {
    let mut reader = Reader::new(data);
    decode_scalar_types(&mut reader)
}

/// Encodes a ScalarTypes to deterministic JSON format.
pub fn to_json_scalar_types(msg: &ScalarTypes) -> std::result::Result<String, String> {
    let mut result = String::new();
    result.push_str("{");

    result.push_str("\"bool_val\":");
    result.push_str(if msg.bool_val { "true" } else { "false" });

    result.push_str(",");
    result.push_str("\"int8_val\":");
    result.push_str("\"");
    result.push_str(&msg.int8_val.to_string());
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"int16_val\":");
    result.push_str("\"");
    result.push_str(&msg.int16_val.to_string());
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"int32_val\":");
    result.push_str("\"");
    result.push_str(&msg.int32_val.to_string());
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"int64_val\":");
    result.push_str("\"");
    result.push_str(&cramberry::json::format_i64_to_string(msg.int64_val));
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"uint8_val\":");
    result.push_str("\"");
    result.push_str(&msg.uint8_val.to_string());
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"uint16_val\":");
    result.push_str("\"");
    result.push_str(&msg.uint16_val.to_string());
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"uint32_val\":");
    result.push_str("\"");
    result.push_str(&msg.uint32_val.to_string());
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"uint64_val\":");
    result.push_str("\"");
    result.push_str(&cramberry::json::format_u64_to_string(msg.uint64_val));
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"float32_val\":");
    result.push_str(&cramberry::json::format_f32(msg.float32_val).map_err(|e| e.to_string())?);

    result.push_str(",");
    result.push_str("\"float64_val\":");
    result.push_str(&cramberry::json::format_f64(msg.float64_val).map_err(|e| e.to_string())?);

    result.push_str(",");
    result.push_str("\"string_val\":");
    result.push_str(&cramberry::json::escape_json_string(&msg.string_val));

    result.push_str(",");
    result.push_str("\"bytes_val\":");
    result.push_str("\"");
    result.push_str(&cramberry::json::encode_base64(&msg.bytes_val));
    result.push_str("\"");

    result.push_str("}");
    Ok(result)
}

/// Decodes a ScalarTypes from JSON format.
pub fn from_json_scalar_types(json: &str) -> std::result::Result<ScalarTypes, String> {
    let parsed: serde_json::Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    let obj = parsed.as_object()
        .ok_or_else(|| "expected JSON object".to_string())?;

    // Check for unknown fields (strict mode)
    let allowed_fields: std::collections::HashSet<&str> = [
        "bool_val",
        "int8_val",
        "int16_val",
        "int32_val",
        "int64_val",
        "uint8_val",
        "uint16_val",
        "uint32_val",
        "uint64_val",
        "float32_val",
        "float64_val",
        "string_val",
        "bytes_val",
    ].iter().copied().collect();

    for key in obj.keys() {
        if !allowed_fields.contains(key.as_str()) {
            return Err(format!("unknown field: {}", key));
        }
    }

    let mut msg: ScalarTypes = Default::default();

    // Decode fields

    if let Some(value) = obj.get("bool_val") {
        msg.bool_val = value.as_bool().ok_or_else(|| "expected boolean".to_string())?;
    }

    if let Some(value) = obj.get("int8_val") {
        msg.int8_val = cramberry::json::parse_i32_from_json(value)? as i8;
    }

    if let Some(value) = obj.get("int16_val") {
        msg.int16_val = cramberry::json::parse_i32_from_json(value)? as i16;
    }

    if let Some(value) = obj.get("int32_val") {
        msg.int32_val = cramberry::json::parse_i32_from_json(value)?;
    }

    if let Some(value) = obj.get("int64_val") {
        msg.int64_val = cramberry::json::parse_i64_from_json(value)?;
    }

    if let Some(value) = obj.get("uint8_val") {
        msg.uint8_val = cramberry::json::parse_u32_from_json(value)? as u8;
    }

    if let Some(value) = obj.get("uint16_val") {
        msg.uint16_val = cramberry::json::parse_u32_from_json(value)? as u16;
    }

    if let Some(value) = obj.get("uint32_val") {
        msg.uint32_val = cramberry::json::parse_u32_from_json(value)?;
    }

    if let Some(value) = obj.get("uint64_val") {
        msg.uint64_val = cramberry::json::parse_u64_from_json(value)?;
    }

    if let Some(value) = obj.get("float32_val") {
        msg.float32_val = value.as_f64().ok_or_else(|| "expected number".to_string())? as f32;
    }

    if let Some(value) = obj.get("float64_val") {
        msg.float64_val = value.as_f64().ok_or_else(|| "expected number".to_string())? as f64;
    }

    if let Some(value) = obj.get("string_val") {
        msg.string_val = value.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
    }

    if let Some(value) = obj.get("bytes_val") {
        let s = value.as_str().ok_or_else(|| "expected string".to_string())?;
        msg.bytes_val = cramberry::json::decode_base64(s).map_err(|e| e.to_string())?;
    }


    Ok(msg)
}


#[derive(Debug, Clone, PartialEq, Default)]
#[derive(Serialize, Deserialize)]
pub struct RepeatedTypes {
    #[serde(rename = "strings")]
    pub strings: Vec<String>,
    #[serde(rename = "ints")]
    pub ints: Vec<i64>,
    #[serde(rename = "bools")]
    pub bools: Vec<bool>,
}

/// Encodes a RepeatedTypes to the writer.
pub fn encode_repeated_types(writer: &mut Writer, msg: &RepeatedTypes) -> Result<()> {

    // Field 1: strings
    if !msg.strings.is_empty() {
        writer.write_tag(1, WireType::Bytes)?;
        {
        let mut sub_writer = Writer::new();
        sub_writer.write_varint(msg.strings.len() as u32)?;
        for elem in &msg.strings {
            sub_writer.write_string(elem)?;
        }
        writer.write_length_prefixed_bytes(sub_writer.as_bytes())
    }?;
    }

    // Field 2: ints
    if !msg.ints.is_empty() {
        writer.write_tag(2, WireType::Bytes)?;
        {
        let mut sub_writer = Writer::new();
        sub_writer.write_varint(msg.ints.len() as u32)?;
        for elem in &msg.ints {
            sub_writer.write_svarint64(*elem)?;
        }
        writer.write_length_prefixed_bytes(sub_writer.as_bytes())
    }?;
    }

    // Field 3: bools
    if !msg.bools.is_empty() {
        writer.write_tag(3, WireType::Bytes)?;
        {
        let mut sub_writer = Writer::new();
        sub_writer.write_varint(msg.bools.len() as u32)?;
        for elem in &msg.bools {
            sub_writer.write_bool(*elem)?;
        }
        writer.write_length_prefixed_bytes(sub_writer.as_bytes())
    }?;
    }

    // End marker
    writer.write_end_marker()?;
    Ok(())
}

/// Decodes a RepeatedTypes from the reader.
pub fn decode_repeated_types(reader: &mut Reader) -> Result<RepeatedTypes> {
    let mut strings: Vec<String> = Default::default();
    let mut ints: Vec<i64> = Default::default();
    let mut bools: Vec<bool> = Default::default();

    loop {
        let tag = reader.read_tag()?;
        if tag.field_number == 0 { break; } // End marker

        match tag.field_number {
            1 => strings = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut reader = Reader::new(__data);
            let len = reader.read_varint()? as usize;
            let mut result = Vec::with_capacity(len);
            for _ in 0..len {
                result.push(reader.read_string()?.to_string());
            }
            result
        },
            2 => ints = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut reader = Reader::new(__data);
            let len = reader.read_varint()? as usize;
            let mut result = Vec::with_capacity(len);
            for _ in 0..len {
                result.push(reader.read_svarint64()?);
            }
            result
        },
            3 => bools = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut reader = Reader::new(__data);
            let len = reader.read_varint()? as usize;
            let mut result = Vec::with_capacity(len);
            for _ in 0..len {
                result.push(reader.read_bool()?);
            }
            result
        },
            _ => reader.skip_value(tag.wire_type)?,
        }
    }

    Ok(RepeatedTypes {
        strings,
        ints,
        bools,
    })
}

/// Marshals a RepeatedTypes to bytes.
pub fn marshal_repeated_types(msg: &RepeatedTypes) -> Result<Vec<u8>> {
    let mut writer = Writer::new();
    encode_repeated_types(&mut writer, msg)?;
    Ok(writer.into_bytes())
}

/// Unmarshals a RepeatedTypes from bytes.
pub fn unmarshal_repeated_types(data: &[u8]) -> Result<RepeatedTypes> {
    let mut reader = Reader::new(data);
    decode_repeated_types(&mut reader)
}

/// Encodes a RepeatedTypes to deterministic JSON format.
pub fn to_json_repeated_types(msg: &RepeatedTypes) -> std::result::Result<String, String> {
    let mut result = String::new();
    result.push_str("{");

    result.push_str("\"strings\":");
    result.push_str("[");
    for (i, elem) in msg.strings.iter().enumerate() {
        if i > 0 { result.push_str(","); }
        result.push_str(&cramberry::json::escape_json_string(&(*elem)));
    }
    result.push_str("]");

    result.push_str(",");
    result.push_str("\"ints\":");
    result.push_str("[");
    for (i, elem) in msg.ints.iter().enumerate() {
        if i > 0 { result.push_str(","); }
        result.push_str("\"");
        result.push_str(&cramberry::json::format_i64_to_string((*elem)));
        result.push_str("\"");
    }
    result.push_str("]");

    result.push_str(",");
    result.push_str("\"bools\":");
    result.push_str("[");
    for (i, elem) in msg.bools.iter().enumerate() {
        if i > 0 { result.push_str(","); }
        result.push_str(if (*elem) { "true" } else { "false" });
    }
    result.push_str("]");

    result.push_str("}");
    Ok(result)
}

/// Decodes a RepeatedTypes from JSON format.
pub fn from_json_repeated_types(json: &str) -> std::result::Result<RepeatedTypes, String> {
    let parsed: serde_json::Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    let obj = parsed.as_object()
        .ok_or_else(|| "expected JSON object".to_string())?;

    // Check for unknown fields (strict mode)
    let allowed_fields: std::collections::HashSet<&str> = [
        "strings",
        "ints",
        "bools",
    ].iter().copied().collect();

    for key in obj.keys() {
        if !allowed_fields.contains(key.as_str()) {
            return Err(format!("unknown field: {}", key));
        }
    }

    let mut msg: RepeatedTypes = Default::default();

    // Decode fields

    if let Some(value) = obj.get("strings") {
    let arr = value.as_array().ok_or_else(|| "expected array".to_string())?;
    msg.strings = Vec::new();
    for elem in arr {
        let mut decoded: String = Default::default();
        decoded = elem.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
        msg.strings.push(decoded);
    }
    }

    if let Some(value) = obj.get("ints") {
    let arr = value.as_array().ok_or_else(|| "expected array".to_string())?;
    msg.ints = Vec::new();
    for elem in arr {
        let mut decoded: i64 = Default::default();
        decoded = cramberry::json::parse_i64_from_json(elem)?;
        msg.ints.push(decoded);
    }
    }

    if let Some(value) = obj.get("bools") {
    let arr = value.as_array().ok_or_else(|| "expected array".to_string())?;
    msg.bools = Vec::new();
    for elem in arr {
        let mut decoded: bool = Default::default();
        decoded = elem.as_bool().ok_or_else(|| "expected boolean".to_string())?;
        msg.bools.push(decoded);
    }
    }


    Ok(msg)
}


#[derive(Debug, Clone, PartialEq, Default)]
#[derive(Serialize, Deserialize)]
pub struct MapTypes {
    #[serde(rename = "string_map")]
    pub string_map: std::collections::HashMap<String, String>,
    #[serde(rename = "int_map")]
    pub int_map: std::collections::HashMap<String, i64>,
    #[serde(rename = "int_keyed")]
    pub int_keyed: std::collections::HashMap<i32, String>,
    #[serde(rename = "uint_keyed")]
    pub uint_keyed: std::collections::HashMap<u64, String>,
}

/// Encodes a MapTypes to the writer.
pub fn encode_map_types(writer: &mut Writer, msg: &MapTypes) -> Result<()> {

    // Field 1: string_map
    writer.write_tag(1, WireType::Bytes)?;
    {
        use cramberry::CompareKeys;
        let mut __entries: Vec<_> = msg.string_map.iter().collect();
        __entries.sort_by(|a, b| a.0.cramberry_cmp(b.0));
        let mut sub_writer = Writer::new();
        sub_writer.write_varint(__entries.len() as u32)?;
        for (k, v) in __entries {
            sub_writer.write_string(k)?;
            sub_writer.write_string(v)?;
        }
        writer.write_length_prefixed_bytes(sub_writer.as_bytes())
    }?;

    // Field 2: int_map
    writer.write_tag(2, WireType::Bytes)?;
    {
        use cramberry::CompareKeys;
        let mut __entries: Vec<_> = msg.int_map.iter().collect();
        __entries.sort_by(|a, b| a.0.cramberry_cmp(b.0));
        let mut sub_writer = Writer::new();
        sub_writer.write_varint(__entries.len() as u32)?;
        for (k, v) in __entries {
            sub_writer.write_string(k)?;
            sub_writer.write_svarint64(*v)?;
        }
        writer.write_length_prefixed_bytes(sub_writer.as_bytes())
    }?;

    // Field 3: int_keyed
    writer.write_tag(3, WireType::Bytes)?;
    {
        use cramberry::CompareKeys;
        let mut __entries: Vec<_> = msg.int_keyed.iter().collect();
        __entries.sort_by(|a, b| a.0.cramberry_cmp(b.0));
        let mut sub_writer = Writer::new();
        sub_writer.write_varint(__entries.len() as u32)?;
        for (k, v) in __entries {
            sub_writer.write_svarint(*k)?;
            sub_writer.write_string(v)?;
        }
        writer.write_length_prefixed_bytes(sub_writer.as_bytes())
    }?;

    // Field 4: uint_keyed
    writer.write_tag(4, WireType::Bytes)?;
    {
        use cramberry::CompareKeys;
        let mut __entries: Vec<_> = msg.uint_keyed.iter().collect();
        __entries.sort_by(|a, b| a.0.cramberry_cmp(b.0));
        let mut sub_writer = Writer::new();
        sub_writer.write_varint(__entries.len() as u32)?;
        for (k, v) in __entries {
            sub_writer.write_varint64(*k)?;
            sub_writer.write_string(v)?;
        }
        writer.write_length_prefixed_bytes(sub_writer.as_bytes())
    }?;

    // End marker
    writer.write_end_marker()?;
    Ok(())
}

/// Decodes a MapTypes from the reader.
pub fn decode_map_types(reader: &mut Reader) -> Result<MapTypes> {
    let mut string_map: std::collections::HashMap<String, String> = Default::default();
    let mut int_map: std::collections::HashMap<String, i64> = Default::default();
    let mut int_keyed: std::collections::HashMap<i32, String> = Default::default();
    let mut uint_keyed: std::collections::HashMap<u64, String> = Default::default();

    loop {
        let tag = reader.read_tag()?;
        if tag.field_number == 0 { break; } // End marker

        match tag.field_number {
            1 => string_map = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut reader = Reader::new(__data);
            let len = reader.read_varint()? as usize;
            let mut result = std::collections::HashMap::with_capacity(len);
            for _ in 0..len {
                let k = reader.read_string()?.to_string();
                let v = reader.read_string()?.to_string();
                result.insert(k, v);
            }
            result
        },
            2 => int_map = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut reader = Reader::new(__data);
            let len = reader.read_varint()? as usize;
            let mut result = std::collections::HashMap::with_capacity(len);
            for _ in 0..len {
                let k = reader.read_string()?.to_string();
                let v = reader.read_svarint64()?;
                result.insert(k, v);
            }
            result
        },
            3 => int_keyed = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut reader = Reader::new(__data);
            let len = reader.read_varint()? as usize;
            let mut result = std::collections::HashMap::with_capacity(len);
            for _ in 0..len {
                let k = reader.read_svarint()?;
                let v = reader.read_string()?.to_string();
                result.insert(k, v);
            }
            result
        },
            4 => uint_keyed = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut reader = Reader::new(__data);
            let len = reader.read_varint()? as usize;
            let mut result = std::collections::HashMap::with_capacity(len);
            for _ in 0..len {
                let k = reader.read_varint64()?;
                let v = reader.read_string()?.to_string();
                result.insert(k, v);
            }
            result
        },
            _ => reader.skip_value(tag.wire_type)?,
        }
    }

    Ok(MapTypes {
        string_map,
        int_map,
        int_keyed,
        uint_keyed,
    })
}

/// Marshals a MapTypes to bytes.
pub fn marshal_map_types(msg: &MapTypes) -> Result<Vec<u8>> {
    let mut writer = Writer::new();
    encode_map_types(&mut writer, msg)?;
    Ok(writer.into_bytes())
}

/// Unmarshals a MapTypes from bytes.
pub fn unmarshal_map_types(data: &[u8]) -> Result<MapTypes> {
    let mut reader = Reader::new(data);
    decode_map_types(&mut reader)
}

/// Encodes a MapTypes to deterministic JSON format.
pub fn to_json_map_types(msg: &MapTypes) -> std::result::Result<String, String> {
    let mut result = String::new();
    result.push_str("{");

    result.push_str("\"string_map\":");
    {
        result.push_str("{");
        let mut keys: Vec<String> = msg.string_map.keys().map(|k| k.to_string()).collect();
        cramberry::json::sort_map_keys_lexicographic(&mut keys);
        for (i, key_str) in keys.iter().enumerate() {
            if i > 0 { result.push_str(","); }
            result.push_str(&cramberry::json::escape_json_string(key_str));
            result.push_str(":");
            let k = key_str.as_str();
            let v = msg.string_map.get(k).unwrap();
            result.push_str(&cramberry::json::escape_json_string(&(*v)));
        }
        result.push_str("}");
    }

    result.push_str(",");
    result.push_str("\"int_map\":");
    {
        result.push_str("{");
        let mut keys: Vec<String> = msg.int_map.keys().map(|k| k.to_string()).collect();
        cramberry::json::sort_map_keys_lexicographic(&mut keys);
        for (i, key_str) in keys.iter().enumerate() {
            if i > 0 { result.push_str(","); }
            result.push_str(&cramberry::json::escape_json_string(key_str));
            result.push_str(":");
            let k = key_str.as_str();
            let v = msg.int_map.get(k).unwrap();
            result.push_str("\"");
            result.push_str(&cramberry::json::format_i64_to_string((*v)));
            result.push_str("\"");
        }
        result.push_str("}");
    }

    result.push_str(",");
    result.push_str("\"int_keyed\":");
    {
        result.push_str("{");
        let mut keys: Vec<String> = msg.int_keyed.keys().map(|k| k.to_string()).collect();
        cramberry::json::sort_map_keys_lexicographic(&mut keys);
        for (i, key_str) in keys.iter().enumerate() {
            if i > 0 { result.push_str(","); }
            result.push_str(&cramberry::json::escape_json_string(key_str));
            result.push_str(":");
            let k: i32 = key_str.parse().unwrap();
            let v = msg.int_keyed.get(&k).unwrap();
            result.push_str(&cramberry::json::escape_json_string(&(*v)));
        }
        result.push_str("}");
    }

    result.push_str(",");
    result.push_str("\"uint_keyed\":");
    {
        result.push_str("{");
        let mut keys: Vec<String> = msg.uint_keyed.keys().map(|k| k.to_string()).collect();
        cramberry::json::sort_map_keys_lexicographic(&mut keys);
        for (i, key_str) in keys.iter().enumerate() {
            if i > 0 { result.push_str(","); }
            result.push_str(&cramberry::json::escape_json_string(key_str));
            result.push_str(":");
            let k: u64 = key_str.parse().unwrap();
            let v = msg.uint_keyed.get(&k).unwrap();
            result.push_str(&cramberry::json::escape_json_string(&(*v)));
        }
        result.push_str("}");
    }

    result.push_str("}");
    Ok(result)
}

/// Decodes a MapTypes from JSON format.
pub fn from_json_map_types(json: &str) -> std::result::Result<MapTypes, String> {
    let parsed: serde_json::Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    let obj = parsed.as_object()
        .ok_or_else(|| "expected JSON object".to_string())?;

    // Check for unknown fields (strict mode)
    let allowed_fields: std::collections::HashSet<&str> = [
        "string_map",
        "int_map",
        "int_keyed",
        "uint_keyed",
    ].iter().copied().collect();

    for key in obj.keys() {
        if !allowed_fields.contains(key.as_str()) {
            return Err(format!("unknown field: {}", key));
        }
    }

    let mut msg: MapTypes = Default::default();

    // Decode fields

    if let Some(value) = obj.get("string_map") {
    let map_obj = value.as_object().ok_or_else(|| "expected object".to_string())?;
    msg.string_map = std::collections::HashMap::new();
    for (key_str, val) in map_obj {
        let k = key_str.to_string();
        let mut v: String = Default::default();
        v = val.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
        msg.string_map.insert(k, v);
    }
    }

    if let Some(value) = obj.get("int_map") {
    let map_obj = value.as_object().ok_or_else(|| "expected object".to_string())?;
    msg.int_map = std::collections::HashMap::new();
    for (key_str, val) in map_obj {
        let k = key_str.to_string();
        let mut v: i64 = Default::default();
        v = cramberry::json::parse_i64_from_json(val)?;
        msg.int_map.insert(k, v);
    }
    }

    if let Some(value) = obj.get("int_keyed") {
    let map_obj = value.as_object().ok_or_else(|| "expected object".to_string())?;
    msg.int_keyed = std::collections::HashMap::new();
    for (key_str, val) in map_obj {
        let k: i32 = key_str.parse().map_err(|e| format!("invalid key: {}", e))?;
        let mut v: String = Default::default();
        v = val.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
        msg.int_keyed.insert(k, v);
    }
    }

    if let Some(value) = obj.get("uint_keyed") {
    let map_obj = value.as_object().ok_or_else(|| "expected object".to_string())?;
    msg.uint_keyed = std::collections::HashMap::new();
    for (key_str, val) in map_obj {
        let k: u64 = key_str.parse().map_err(|e| format!("invalid key: {}", e))?;
        let mut v: String = Default::default();
        v = val.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
        msg.uint_keyed.insert(k, v);
    }
    }


    Ok(msg)
}


#[derive(Debug, Clone, PartialEq, Default)]
#[derive(Serialize, Deserialize)]
pub struct Address {
    #[serde(rename = "street")]
    pub street: String,
    #[serde(rename = "city")]
    pub city: String,
    #[serde(rename = "zip")]
    pub zip: String,
}

/// Encodes a Address to the writer.
pub fn encode_address(writer: &mut Writer, msg: &Address) -> Result<()> {

    // Field 1: street
    if !msg.street.is_empty() {
        writer.write_tag(1, WireType::Bytes)?;
        writer.write_string(&msg.street)?;
    }

    // Field 2: city
    if !msg.city.is_empty() {
        writer.write_tag(2, WireType::Bytes)?;
        writer.write_string(&msg.city)?;
    }

    // Field 3: zip
    if !msg.zip.is_empty() {
        writer.write_tag(3, WireType::Bytes)?;
        writer.write_string(&msg.zip)?;
    }

    // End marker
    writer.write_end_marker()?;
    Ok(())
}

/// Decodes a Address from the reader.
pub fn decode_address(reader: &mut Reader) -> Result<Address> {
    let mut street: String = Default::default();
    let mut city: String = Default::default();
    let mut zip: String = Default::default();

    loop {
        let tag = reader.read_tag()?;
        if tag.field_number == 0 { break; } // End marker

        match tag.field_number {
            1 => street = reader.read_string()?.to_string(),
            2 => city = reader.read_string()?.to_string(),
            3 => zip = reader.read_string()?.to_string(),
            _ => reader.skip_value(tag.wire_type)?,
        }
    }

    Ok(Address {
        street,
        city,
        zip,
    })
}

/// Marshals a Address to bytes.
pub fn marshal_address(msg: &Address) -> Result<Vec<u8>> {
    let mut writer = Writer::new();
    encode_address(&mut writer, msg)?;
    Ok(writer.into_bytes())
}

/// Unmarshals a Address from bytes.
pub fn unmarshal_address(data: &[u8]) -> Result<Address> {
    let mut reader = Reader::new(data);
    decode_address(&mut reader)
}

/// Encodes a Address to deterministic JSON format.
pub fn to_json_address(msg: &Address) -> std::result::Result<String, String> {
    let mut result = String::new();
    result.push_str("{");

    result.push_str("\"street\":");
    result.push_str(&cramberry::json::escape_json_string(&msg.street));

    result.push_str(",");
    result.push_str("\"city\":");
    result.push_str(&cramberry::json::escape_json_string(&msg.city));

    result.push_str(",");
    result.push_str("\"zip\":");
    result.push_str(&cramberry::json::escape_json_string(&msg.zip));

    result.push_str("}");
    Ok(result)
}

/// Decodes a Address from JSON format.
pub fn from_json_address(json: &str) -> std::result::Result<Address, String> {
    let parsed: serde_json::Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    let obj = parsed.as_object()
        .ok_or_else(|| "expected JSON object".to_string())?;

    // Check for unknown fields (strict mode)
    let allowed_fields: std::collections::HashSet<&str> = [
        "street",
        "city",
        "zip",
    ].iter().copied().collect();

    for key in obj.keys() {
        if !allowed_fields.contains(key.as_str()) {
            return Err(format!("unknown field: {}", key));
        }
    }

    let mut msg: Address = Default::default();

    // Decode fields

    if let Some(value) = obj.get("street") {
        msg.street = value.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
    }

    if let Some(value) = obj.get("city") {
        msg.city = value.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
    }

    if let Some(value) = obj.get("zip") {
        msg.zip = value.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
    }


    Ok(msg)
}


#[derive(Debug, Clone, PartialEq, Default)]
#[derive(Serialize, Deserialize)]
pub struct Person {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "age")]
    pub age: i32,
    #[serde(rename = "address")]
    pub address: Address,
    #[serde(rename = "emails")]
    pub emails: Vec<String>,
}

/// Encodes a Person to the writer.
pub fn encode_person(writer: &mut Writer, msg: &Person) -> Result<()> {

    // Field 1: name
    if !msg.name.is_empty() {
        writer.write_tag(1, WireType::Bytes)?;
        writer.write_string(&msg.name)?;
    }

    // Field 2: age
    if msg.age != 0 as i32 {
        writer.write_tag(2, WireType::SVarint)?;
        writer.write_svarint(msg.age)?;
    }

    // Field 3: address
    writer.write_tag(3, WireType::Bytes)?;
    {
        let mut __sub = Writer::new();
        encode_address(&mut __sub, &msg.address)?;
        writer.write_length_prefixed_bytes(__sub.as_bytes())
    }?;

    // Field 4: emails
    if !msg.emails.is_empty() {
        writer.write_tag(4, WireType::Bytes)?;
        {
        let mut sub_writer = Writer::new();
        sub_writer.write_varint(msg.emails.len() as u32)?;
        for elem in &msg.emails {
            sub_writer.write_string(elem)?;
        }
        writer.write_length_prefixed_bytes(sub_writer.as_bytes())
    }?;
    }

    // End marker
    writer.write_end_marker()?;
    Ok(())
}

/// Decodes a Person from the reader.
pub fn decode_person(reader: &mut Reader) -> Result<Person> {
    let mut name: String = Default::default();
    let mut age: i32 = Default::default();
    let mut address: Address = Default::default();
    let mut emails: Vec<String> = Default::default();

    loop {
        let tag = reader.read_tag()?;
        if tag.field_number == 0 { break; } // End marker

        match tag.field_number {
            1 => name = reader.read_string()?.to_string(),
            2 => age = reader.read_svarint()?,
            3 => address = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut __sub = Reader::new(__data);
            decode_address(&mut __sub)?
        },
            4 => emails = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut reader = Reader::new(__data);
            let len = reader.read_varint()? as usize;
            let mut result = Vec::with_capacity(len);
            for _ in 0..len {
                result.push(reader.read_string()?.to_string());
            }
            result
        },
            _ => reader.skip_value(tag.wire_type)?,
        }
    }

    Ok(Person {
        name,
        age,
        address,
        emails,
    })
}

/// Marshals a Person to bytes.
pub fn marshal_person(msg: &Person) -> Result<Vec<u8>> {
    let mut writer = Writer::new();
    encode_person(&mut writer, msg)?;
    Ok(writer.into_bytes())
}

/// Unmarshals a Person from bytes.
pub fn unmarshal_person(data: &[u8]) -> Result<Person> {
    let mut reader = Reader::new(data);
    decode_person(&mut reader)
}

/// Encodes a Person to deterministic JSON format.
pub fn to_json_person(msg: &Person) -> std::result::Result<String, String> {
    let mut result = String::new();
    result.push_str("{");

    result.push_str("\"name\":");
    result.push_str(&cramberry::json::escape_json_string(&msg.name));

    result.push_str(",");
    result.push_str("\"age\":");
    result.push_str("\"");
    result.push_str(&msg.age.to_string());
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"address\":");
    result.push_str(&to_json_address(&msg.address)?);

    result.push_str(",");
    result.push_str("\"emails\":");
    result.push_str("[");
    for (i, elem) in msg.emails.iter().enumerate() {
        if i > 0 { result.push_str(","); }
        result.push_str(&cramberry::json::escape_json_string(&(*elem)));
    }
    result.push_str("]");

    result.push_str("}");
    Ok(result)
}

/// Decodes a Person from JSON format.
pub fn from_json_person(json: &str) -> std::result::Result<Person, String> {
    let parsed: serde_json::Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    let obj = parsed.as_object()
        .ok_or_else(|| "expected JSON object".to_string())?;

    // Check for unknown fields (strict mode)
    let allowed_fields: std::collections::HashSet<&str> = [
        "name",
        "age",
        "address",
        "emails",
    ].iter().copied().collect();

    for key in obj.keys() {
        if !allowed_fields.contains(key.as_str()) {
            return Err(format!("unknown field: {}", key));
        }
    }

    let mut msg: Person = Default::default();

    // Decode fields

    if let Some(value) = obj.get("name") {
        msg.name = value.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
    }

    if let Some(value) = obj.get("age") {
        msg.age = cramberry::json::parse_i32_from_json(value)?;
    }

    if let Some(value) = obj.get("address") {
        msg.address = from_json_address(&value.to_string()).map_err(|e| e.to_string())?;
    }

    if let Some(value) = obj.get("emails") {
    let arr = value.as_array().ok_or_else(|| "expected array".to_string())?;
    msg.emails = Vec::new();
    for elem in arr {
        let mut decoded: String = Default::default();
        decoded = elem.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
        msg.emails.push(decoded);
    }
    }


    Ok(msg)
}


#[derive(Debug, Clone, PartialEq, Default)]
#[derive(Serialize, Deserialize)]
pub struct RequiredFields {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "optional_field")]
    pub optional_field: String,
}

/// Encodes a RequiredFields to the writer.
pub fn encode_required_fields(writer: &mut Writer, msg: &RequiredFields) -> Result<()> {

    // Field 1: id
    if msg.id != 0 as i64 {
        writer.write_tag(1, WireType::SVarint)?;
        writer.write_svarint64(msg.id)?;
    }

    // Field 2: name
    if !msg.name.is_empty() {
        writer.write_tag(2, WireType::Bytes)?;
        writer.write_string(&msg.name)?;
    }

    // Field 3: optional_field
    if !msg.optional_field.is_empty() {
        writer.write_tag(3, WireType::Bytes)?;
        writer.write_string(&msg.optional_field)?;
    }

    // End marker
    writer.write_end_marker()?;
    Ok(())
}

/// Decodes a RequiredFields from the reader.
pub fn decode_required_fields(reader: &mut Reader) -> Result<RequiredFields> {
    let mut id: i64 = Default::default();
    let mut name: String = Default::default();
    let mut optional_field: String = Default::default();

    loop {
        let tag = reader.read_tag()?;
        if tag.field_number == 0 { break; } // End marker

        match tag.field_number {
            1 => id = reader.read_svarint64()?,
            2 => name = reader.read_string()?.to_string(),
            3 => optional_field = reader.read_string()?.to_string(),
            _ => reader.skip_value(tag.wire_type)?,
        }
    }

    Ok(RequiredFields {
        id,
        name,
        optional_field,
    })
}

/// Marshals a RequiredFields to bytes.
pub fn marshal_required_fields(msg: &RequiredFields) -> Result<Vec<u8>> {
    let mut writer = Writer::new();
    encode_required_fields(&mut writer, msg)?;
    Ok(writer.into_bytes())
}

/// Unmarshals a RequiredFields from bytes.
pub fn unmarshal_required_fields(data: &[u8]) -> Result<RequiredFields> {
    let mut reader = Reader::new(data);
    decode_required_fields(&mut reader)
}

/// Encodes a RequiredFields to deterministic JSON format.
pub fn to_json_required_fields(msg: &RequiredFields) -> std::result::Result<String, String> {
    let mut result = String::new();
    result.push_str("{");

    result.push_str("\"id\":");
    result.push_str("\"");
    result.push_str(&cramberry::json::format_i64_to_string(msg.id));
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"name\":");
    result.push_str(&cramberry::json::escape_json_string(&msg.name));

    result.push_str(",");
    result.push_str("\"optional_field\":");
    result.push_str(&cramberry::json::escape_json_string(&msg.optional_field));

    result.push_str("}");
    Ok(result)
}

/// Decodes a RequiredFields from JSON format.
pub fn from_json_required_fields(json: &str) -> std::result::Result<RequiredFields, String> {
    let parsed: serde_json::Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    let obj = parsed.as_object()
        .ok_or_else(|| "expected JSON object".to_string())?;

    // Check for unknown fields (strict mode)
    let allowed_fields: std::collections::HashSet<&str> = [
        "id",
        "name",
        "optional_field",
    ].iter().copied().collect();

    for key in obj.keys() {
        if !allowed_fields.contains(key.as_str()) {
            return Err(format!("unknown field: {}", key));
        }
    }

    let mut msg: RequiredFields = Default::default();

    // Decode fields

    if let Some(value) = obj.get("id") {
        msg.id = cramberry::json::parse_i64_from_json(value)?;
    }

    if let Some(value) = obj.get("name") {
        msg.name = value.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
    }

    if let Some(value) = obj.get("optional_field") {
        msg.optional_field = value.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
    }


    Ok(msg)
}


#[derive(Debug, Clone, PartialEq, Default)]
#[derive(Serialize, Deserialize)]
pub struct OptionalPointer {
    #[serde(rename = "value")]
    pub value: Option<Box<String>>,
    #[serde(rename = "number")]
    pub number: Option<Box<i64>>,
    #[serde(rename = "blob")]
    pub blob: Option<Vec<u8>>,
}

/// Encodes a OptionalPointer to the writer.
pub fn encode_optional_pointer(writer: &mut Writer, msg: &OptionalPointer) -> Result<()> {

    // Field 1: value
    if msg.value.is_some() {
        writer.write_tag(1, WireType::Bytes)?;
        if let Some(inner) = msg.value.as_deref() {
        writer.write_string(&*inner)
    } else {
        Ok(())
    }?;
    }

    // Field 2: number
    if msg.number.is_some() {
        writer.write_tag(2, WireType::Bytes)?;
        if let Some(inner) = msg.number.as_deref() {
        writer.write_svarint64(*inner)
    } else {
        Ok(())
    }?;
    }

    // Field 3: blob
    if msg.blob.is_some() {
        writer.write_tag(3, WireType::Bytes)?;
        {
        let __inner = msg.blob.as_ref().unwrap();
        writer.write_length_prefixed_bytes(&(*__inner))
    }?;
    }

    // End marker
    writer.write_end_marker()?;
    Ok(())
}

/// Decodes a OptionalPointer from the reader.
pub fn decode_optional_pointer(reader: &mut Reader) -> Result<OptionalPointer> {
    let mut value: Option<Box<String>> = Default::default();
    let mut number: Option<Box<i64>> = Default::default();
    let mut blob: Option<Vec<u8>> = Default::default();

    loop {
        let tag = reader.read_tag()?;
        if tag.field_number == 0 { break; } // End marker

        match tag.field_number {
            1 => value = Some(Box::new(reader.read_string()?.to_string())),
            2 => number = Some(Box::new(reader.read_svarint64()?)),
            3 => blob = Some(reader.read_length_prefixed_bytes()?.to_vec()),
            _ => reader.skip_value(tag.wire_type)?,
        }
    }

    Ok(OptionalPointer {
        value,
        number,
        blob,
    })
}

/// Marshals a OptionalPointer to bytes.
pub fn marshal_optional_pointer(msg: &OptionalPointer) -> Result<Vec<u8>> {
    let mut writer = Writer::new();
    encode_optional_pointer(&mut writer, msg)?;
    Ok(writer.into_bytes())
}

/// Unmarshals a OptionalPointer from bytes.
pub fn unmarshal_optional_pointer(data: &[u8]) -> Result<OptionalPointer> {
    let mut reader = Reader::new(data);
    decode_optional_pointer(&mut reader)
}

/// Encodes a OptionalPointer to deterministic JSON format.
pub fn to_json_optional_pointer(msg: &OptionalPointer) -> std::result::Result<String, String> {
    let mut result = String::new();
    result.push_str("{");

    result.push_str("\"value\":");
    if let Some(v) = &msg.value {
            result.push_str(&cramberry::json::escape_json_string(&(**v)));
    } else {
        result.push_str("null");
    }

    result.push_str(",");
    result.push_str("\"number\":");
    if let Some(v) = &msg.number {
            result.push_str("\"");
        result.push_str(&cramberry::json::format_i64_to_string((**v)));
        result.push_str("\"");
    } else {
        result.push_str("null");
    }

    result.push_str(",");
    result.push_str("\"blob\":");
    if let Some(v) = &msg.blob {
            result.push_str("\"");
        result.push_str(&cramberry::json::encode_base64(&v));
        result.push_str("\"");
    } else {
        result.push_str("null");
    }

    result.push_str("}");
    Ok(result)
}

/// Decodes a OptionalPointer from JSON format.
pub fn from_json_optional_pointer(json: &str) -> std::result::Result<OptionalPointer, String> {
    let parsed: serde_json::Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    let obj = parsed.as_object()
        .ok_or_else(|| "expected JSON object".to_string())?;

    // Check for unknown fields (strict mode)
    let allowed_fields: std::collections::HashSet<&str> = [
        "value",
        "number",
        "blob",
    ].iter().copied().collect();

    for key in obj.keys() {
        if !allowed_fields.contains(key.as_str()) {
            return Err(format!("unknown field: {}", key));
        }
    }

    let mut msg: OptionalPointer = Default::default();

    // Decode fields

    if let Some(value) = obj.get("value") {
        if value.is_null() {
            msg.value = None;
        } else {
            let mut v: Box<String> = Box::new(Default::default());
                    (*v) = value.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
            msg.value = Some(v);
        }
    }

    if let Some(value) = obj.get("number") {
        if value.is_null() {
            msg.number = None;
        } else {
            let mut v: Box<i64> = Box::new(Default::default());
                    (*v) = cramberry::json::parse_i64_from_json(value)?;
            msg.number = Some(v);
        }
    }

    if let Some(value) = obj.get("blob") {
        if value.is_null() {
            msg.blob = None;
        } else {
            let mut v: Vec<u8> = Default::default();
                    let s = value.as_str().ok_or_else(|| "expected string".to_string())?;
            v = cramberry::json::decode_base64(s).map_err(|e| e.to_string())?;
            msg.blob = Some(v);
        }
    }


    Ok(msg)
}


#[derive(Debug, Clone, PartialEq, Default)]
#[derive(Serialize, Deserialize)]
pub struct EnumTest {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "statuses")]
    pub statuses: Vec<Status>,
}

/// Encodes a EnumTest to the writer.
pub fn encode_enum_test(writer: &mut Writer, msg: &EnumTest) -> Result<()> {

    // Field 1: status
    writer.write_tag(1, WireType::SVarint)?;
    writer.write_svarint(msg.status as i32)?;

    // Field 2: statuses
    if !msg.statuses.is_empty() {
        writer.write_tag(2, WireType::Bytes)?;
        {
        let mut sub_writer = Writer::new();
        sub_writer.write_varint(msg.statuses.len() as u32)?;
        for elem in &msg.statuses {
            sub_writer.write_svarint(*elem as i32)?;
        }
        writer.write_length_prefixed_bytes(sub_writer.as_bytes())
    }?;
    }

    // End marker
    writer.write_end_marker()?;
    Ok(())
}

/// Decodes a EnumTest from the reader.
pub fn decode_enum_test(reader: &mut Reader) -> Result<EnumTest> {
    let mut status: Status = Default::default();
    let mut statuses: Vec<Status> = Default::default();

    loop {
        let tag = reader.read_tag()?;
        if tag.field_number == 0 { break; } // End marker

        match tag.field_number {
            1 => status = Status::from_i32(reader.read_svarint()?).unwrap_or(Status::Unknown),
            2 => statuses = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut reader = Reader::new(__data);
            let len = reader.read_varint()? as usize;
            let mut result = Vec::with_capacity(len);
            for _ in 0..len {
                result.push(Status::from_i32(reader.read_svarint()?).unwrap_or(Status::Unknown));
            }
            result
        },
            _ => reader.skip_value(tag.wire_type)?,
        }
    }

    Ok(EnumTest {
        status,
        statuses,
    })
}

/// Marshals a EnumTest to bytes.
pub fn marshal_enum_test(msg: &EnumTest) -> Result<Vec<u8>> {
    let mut writer = Writer::new();
    encode_enum_test(&mut writer, msg)?;
    Ok(writer.into_bytes())
}

/// Unmarshals a EnumTest from bytes.
pub fn unmarshal_enum_test(data: &[u8]) -> Result<EnumTest> {
    let mut reader = Reader::new(data);
    decode_enum_test(&mut reader)
}

/// Encodes a EnumTest to deterministic JSON format.
pub fn to_json_enum_test(msg: &EnumTest) -> std::result::Result<String, String> {
    let mut result = String::new();
    result.push_str("{");

    result.push_str("\"status\":");
    result.push_str("\"");
    result.push_str(match msg.status {
        Status::Unknown => "UNKNOWN",
        Status::Active => "ACTIVE",
        Status::Inactive => "INACTIVE",
        Status::Pending => "PENDING",
        _ => "UNKNOWN",
    });
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"statuses\":");
    result.push_str("[");
    for (i, elem) in msg.statuses.iter().enumerate() {
        if i > 0 { result.push_str(","); }
        result.push_str("\"");
        result.push_str(match (*elem) {
                Status::Unknown => "UNKNOWN",
                Status::Active => "ACTIVE",
                Status::Inactive => "INACTIVE",
                Status::Pending => "PENDING",
                _ => "UNKNOWN",
        });
        result.push_str("\"");
    }
    result.push_str("]");

    result.push_str("}");
    Ok(result)
}

/// Decodes a EnumTest from JSON format.
pub fn from_json_enum_test(json: &str) -> std::result::Result<EnumTest, String> {
    let parsed: serde_json::Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    let obj = parsed.as_object()
        .ok_or_else(|| "expected JSON object".to_string())?;

    // Check for unknown fields (strict mode)
    let allowed_fields: std::collections::HashSet<&str> = [
        "status",
        "statuses",
    ].iter().copied().collect();

    for key in obj.keys() {
        if !allowed_fields.contains(key.as_str()) {
            return Err(format!("unknown field: {}", key));
        }
    }

    let mut msg: EnumTest = Default::default();

    // Decode fields

    if let Some(value) = obj.get("status") {
        let str_val = value.as_str().ok_or_else(|| "expected string for enum".to_string())?;
        msg.status = match str_val {
            "UNKNOWN" => Status::Unknown,
            "ACTIVE" => Status::Active,
            "INACTIVE" => Status::Inactive,
            "PENDING" => Status::Pending,
            _ => return Err(format!("unknown enum value: {}", str_val)),
        };
    }

    if let Some(value) = obj.get("statuses") {
    let arr = value.as_array().ok_or_else(|| "expected array".to_string())?;
    msg.statuses = Vec::new();
    for elem in arr {
        let mut decoded: Status = Default::default();
        let str_val = elem.as_str().ok_or_else(|| "expected string for enum".to_string())?;
        decoded = match str_val {
            "UNKNOWN" => Status::Unknown,
            "ACTIVE" => Status::Active,
            "INACTIVE" => Status::Inactive,
            "PENDING" => Status::Pending,
            _ => return Err(format!("unknown enum value: {}", str_val)),
        };
        msg.statuses.push(decoded);
    }
    }


    Ok(msg)
}


#[derive(Debug, Clone, PartialEq, Default)]
#[derive(Serialize, Deserialize)]
pub struct EmptyMessage {
}

/// Encodes a EmptyMessage to the writer.
pub fn encode_empty_message(writer: &mut Writer, msg: &EmptyMessage) -> Result<()> {

    // End marker
    writer.write_end_marker()?;
    Ok(())
}

/// Decodes a EmptyMessage from the reader.
pub fn decode_empty_message(reader: &mut Reader) -> Result<EmptyMessage> {

    loop {
        let tag = reader.read_tag()?;
        if tag.field_number == 0 { break; } // End marker

        match tag.field_number {
            _ => reader.skip_value(tag.wire_type)?,
        }
    }

    Ok(EmptyMessage {
    })
}

/// Marshals a EmptyMessage to bytes.
pub fn marshal_empty_message(msg: &EmptyMessage) -> Result<Vec<u8>> {
    let mut writer = Writer::new();
    encode_empty_message(&mut writer, msg)?;
    Ok(writer.into_bytes())
}

/// Unmarshals a EmptyMessage from bytes.
pub fn unmarshal_empty_message(data: &[u8]) -> Result<EmptyMessage> {
    let mut reader = Reader::new(data);
    decode_empty_message(&mut reader)
}

/// Encodes a EmptyMessage to deterministic JSON format.
pub fn to_json_empty_message(msg: &EmptyMessage) -> std::result::Result<String, String> {
    let mut result = String::new();
    result.push_str("{");

    result.push_str("}");
    Ok(result)
}

/// Decodes a EmptyMessage from JSON format.
pub fn from_json_empty_message(json: &str) -> std::result::Result<EmptyMessage, String> {
    let parsed: serde_json::Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    let obj = parsed.as_object()
        .ok_or_else(|| "expected JSON object".to_string())?;

    // Check for unknown fields (strict mode)
    let allowed_fields: std::collections::HashSet<&str> = [
    ].iter().copied().collect();

    for key in obj.keys() {
        if !allowed_fields.contains(key.as_str()) {
            return Err(format!("unknown field: {}", key));
        }
    }

    let mut msg: EmptyMessage = Default::default();

    // Decode fields


    Ok(msg)
}


#[derive(Debug, Clone, PartialEq, Default)]
#[derive(Serialize, Deserialize)]
pub struct AllZeroValues {
    #[serde(rename = "zero_int")]
    pub zero_int: i64,
    #[serde(rename = "zero_string")]
    pub zero_string: String,
    #[serde(rename = "zero_bool")]
    pub zero_bool: bool,
    #[serde(rename = "empty_array")]
    pub empty_array: Vec<String>,
}

/// Encodes a AllZeroValues to the writer.
pub fn encode_all_zero_values(writer: &mut Writer, msg: &AllZeroValues) -> Result<()> {

    // Field 1: zero_int
    if msg.zero_int != 0 as i64 {
        writer.write_tag(1, WireType::SVarint)?;
        writer.write_svarint64(msg.zero_int)?;
    }

    // Field 2: zero_string
    if !msg.zero_string.is_empty() {
        writer.write_tag(2, WireType::Bytes)?;
        writer.write_string(&msg.zero_string)?;
    }

    // Field 3: zero_bool
    if msg.zero_bool {
        writer.write_tag(3, WireType::Varint)?;
        writer.write_bool(msg.zero_bool)?;
    }

    // Field 4: empty_array
    if !msg.empty_array.is_empty() {
        writer.write_tag(4, WireType::Bytes)?;
        {
        let mut sub_writer = Writer::new();
        sub_writer.write_varint(msg.empty_array.len() as u32)?;
        for elem in &msg.empty_array {
            sub_writer.write_string(elem)?;
        }
        writer.write_length_prefixed_bytes(sub_writer.as_bytes())
    }?;
    }

    // End marker
    writer.write_end_marker()?;
    Ok(())
}

/// Decodes a AllZeroValues from the reader.
pub fn decode_all_zero_values(reader: &mut Reader) -> Result<AllZeroValues> {
    let mut zero_int: i64 = Default::default();
    let mut zero_string: String = Default::default();
    let mut zero_bool: bool = Default::default();
    let mut empty_array: Vec<String> = Default::default();

    loop {
        let tag = reader.read_tag()?;
        if tag.field_number == 0 { break; } // End marker

        match tag.field_number {
            1 => zero_int = reader.read_svarint64()?,
            2 => zero_string = reader.read_string()?.to_string(),
            3 => zero_bool = reader.read_bool()?,
            4 => empty_array = {
            let __data = reader.read_length_prefixed_bytes()?;
            let mut reader = Reader::new(__data);
            let len = reader.read_varint()? as usize;
            let mut result = Vec::with_capacity(len);
            for _ in 0..len {
                result.push(reader.read_string()?.to_string());
            }
            result
        },
            _ => reader.skip_value(tag.wire_type)?,
        }
    }

    Ok(AllZeroValues {
        zero_int,
        zero_string,
        zero_bool,
        empty_array,
    })
}

/// Marshals a AllZeroValues to bytes.
pub fn marshal_all_zero_values(msg: &AllZeroValues) -> Result<Vec<u8>> {
    let mut writer = Writer::new();
    encode_all_zero_values(&mut writer, msg)?;
    Ok(writer.into_bytes())
}

/// Unmarshals a AllZeroValues from bytes.
pub fn unmarshal_all_zero_values(data: &[u8]) -> Result<AllZeroValues> {
    let mut reader = Reader::new(data);
    decode_all_zero_values(&mut reader)
}

/// Encodes a AllZeroValues to deterministic JSON format.
pub fn to_json_all_zero_values(msg: &AllZeroValues) -> std::result::Result<String, String> {
    let mut result = String::new();
    result.push_str("{");

    result.push_str("\"zero_int\":");
    result.push_str("\"");
    result.push_str(&cramberry::json::format_i64_to_string(msg.zero_int));
    result.push_str("\"");

    result.push_str(",");
    result.push_str("\"zero_string\":");
    result.push_str(&cramberry::json::escape_json_string(&msg.zero_string));

    result.push_str(",");
    result.push_str("\"zero_bool\":");
    result.push_str(if msg.zero_bool { "true" } else { "false" });

    result.push_str(",");
    result.push_str("\"empty_array\":");
    result.push_str("[");
    for (i, elem) in msg.empty_array.iter().enumerate() {
        if i > 0 { result.push_str(","); }
        result.push_str(&cramberry::json::escape_json_string(&(*elem)));
    }
    result.push_str("]");

    result.push_str("}");
    Ok(result)
}

/// Decodes a AllZeroValues from JSON format.
pub fn from_json_all_zero_values(json: &str) -> std::result::Result<AllZeroValues, String> {
    let parsed: serde_json::Value = serde_json::from_str(json)
        .map_err(|e| format!("JSON parse error: {}", e))?;

    let obj = parsed.as_object()
        .ok_or_else(|| "expected JSON object".to_string())?;

    // Check for unknown fields (strict mode)
    let allowed_fields: std::collections::HashSet<&str> = [
        "zero_int",
        "zero_string",
        "zero_bool",
        "empty_array",
    ].iter().copied().collect();

    for key in obj.keys() {
        if !allowed_fields.contains(key.as_str()) {
            return Err(format!("unknown field: {}", key));
        }
    }

    let mut msg: AllZeroValues = Default::default();

    // Decode fields

    if let Some(value) = obj.get("zero_int") {
        msg.zero_int = cramberry::json::parse_i64_from_json(value)?;
    }

    if let Some(value) = obj.get("zero_string") {
        msg.zero_string = value.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
    }

    if let Some(value) = obj.get("zero_bool") {
        msg.zero_bool = value.as_bool().ok_or_else(|| "expected boolean".to_string())?;
    }

    if let Some(value) = obj.get("empty_array") {
    let arr = value.as_array().ok_or_else(|| "expected array".to_string())?;
    msg.empty_array = Vec::new();
    for elem in arr {
        let mut decoded: String = Default::default();
        decoded = elem.as_str().ok_or_else(|| "expected string".to_string())?.to_string();
        msg.empty_array.push(decoded);
    }
    }


    Ok(msg)
}



